import {
  BookOpen,
  BookText,
  Building2,
  Calculator,
  DollarSign,
  GraduationCap,
  LogIn,
  Search,
} from 'lucide-react';

export const ToastVariant = {
  SUCCESS: 'success',
  WARNING: 'warning',
  ERROR: 'error',
};
export const ResponseStatus = {
  CREATED: 201,
  SUCCESS: 204,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
};
export const ResponseTitle = {
  NOT_FOUND: 'Not Found',
  BAD_REQUEST: 'Bad Request',
};
export const HAVE_BEEN_DELETED = ' have been deleted';
export const DELETE_FAILED = 'Delete failed';
export const UPDATE_SUCCESSFULLY = 'Update successfully';
export const CREATE_SUCCESSFULLY = 'Create successfully';
export const UPDATE_FAILED = 'Update failed';
export const CREATE_FAILED = 'Create failed';
export const ADD_PRODUCT_INTO_WAREHOUSE_SUCCESSFULLY = 'Add product(s) into warehouse successfully';
export const TOAST_DURATION = 4000;
export const CUSTOMER_URL = '/customers';
export const COUNTRY_URL = '/location/countries';
export const STATE_OR_PROVINCE_URL = '/location/state-or-provinces';

export const DEFAULT_PAGE_SIZE = 10;
export const DEFAULT_PAGE_NUMBER = 0;
export const FORMAT_DATE_YYYY_MM_DD_HH_MM = 'YYYYMMDDHHmmss';

export const studentMenuItems = [
  {
    title: 'Scholarship Directory',
    description: 'Find scholarships by category.',
    icon: BookOpen,
    href: '/scholarships',
  },
  {
    title: 'College Search',
    description: "Find the college that's right for you.",
    icon: Search,
    href: '/colleges',
  },
  {
    title: 'Student Resources',
    description: 'Top resources for your scholarship journey.',
    icon: GraduationCap,
    href: '/resources',
  },
  {
    title: 'College Matches',
    description: 'Personalized list of colleges that fit you.',
    icon: Building2,
    href: '/matches',
  },
  {
    title: 'Student Loans',
    description: 'Explore loan options to help pay for college.',
    icon: DollarSign,
    href: '/loans',
  },
  {
    title: 'Calculators',
    description: 'Calculate your cost to attend college.',
    icon: Calculator,
    href: '/calculators',
  },
];

export const scholarshipProviderMenuItems = [
  {
    title: 'Submit Scholarship',
    description: 'share your scholarship with eligibility students.',
    icon: BookOpen,
    href: '/provider/scholarships/create',
  },
  {
    title: 'Provider Log In',
    description: 'Log in to your provider account.',
    icon: LogIn,
    href: '/provider/login',
  },
  {
    title: 'Guidelines ',
    description: 'Guidelines for submitting scholarships.',
    icon: BookText,
    href: '/provider/guidelines',
  },
];

export const YEARS = Array.from({ length: 201 }, (_, i) => 2100 - i).map((year) => ({
  value: year,
  label: String(year),
}));

export const COUNTRIES = [
  { value: 'Afghanistan', label: 'Afghanistan' },
  { value: 'land Islands', label: 'land Islands' },
  { value: 'Albania', label: 'Albania' },
  { value: 'Algeria', label: 'Algeria' },
  { value: 'American Samoa', label: 'American Samoa' },
  { value: 'AndorrA', label: 'AndorrA' },
  { value: 'Angola', label: 'Angola' },
  { value: 'Anguilla', label: 'Anguilla' },
  { value: 'Antarctica', label: 'Antarctica' },
  { value: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Armenia', label: 'Armenia' },
  { value: 'Aruba', label: 'Aruba' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Azerbaijan', label: 'Azerbaijan' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Bahrain', label: 'Bahrain' },
  { value: 'Bangladesh', label: 'Bangladesh' },
  { value: 'Barbados', label: 'Barbados' },
  { value: 'Belarus', label: 'Belarus' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Belize', label: 'Belize' },
  { value: 'Benin', label: 'Benin' },
  { value: 'Bermuda', label: 'Bermuda' },
  { value: 'Bhutan', label: 'Bhutan' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
  { value: 'Botswana', label: 'Botswana' },
  { value: 'Bouvet Island', label: 'Bouvet Island' },
  { value: 'Brazil', label: 'Brazil' },
  { value: 'British Indian Ocean Territory', label: 'British Indian Ocean Territory' },
  { value: 'Brunei Darussalam', label: 'Brunei Darussalam' },
  { value: 'Bulgaria', label: 'Bulgaria' },
  { value: 'Burkina Faso', label: 'Burkina Faso' },
  { value: 'Burundi', label: 'Burundi' },
  { value: 'Cambodia', label: 'Cambodia' },
  { value: 'Cameroon', label: 'Cameroon' },
  { value: 'Canada', label: 'Canada' },
  { value: 'Cape Verde', label: 'Cape Verde' },
  { value: 'Cayman Islands', label: 'Cayman Islands' },
  { value: 'Central African Republic', label: 'Central African Republic' },
  { value: 'Chad', label: 'Chad' },
  { value: 'Chile', label: 'Chile' },
  { value: 'China', label: 'China' },
  { value: 'Christmas Island', label: 'Christmas Island' },
  { value: 'Cocos (Keeling) Islands', label: 'Cocos (Keeling) Islands' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Comoros', label: 'Comoros' },
  { value: 'Congo', label: 'Congo' },
  {
    value: 'Congo, The Democratic Republic of the',
    label: 'Congo, The Democratic Republic of the',
  },
  { value: 'Cook Islands', label: 'Cook Islands' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'Cote D"Ivoire', label: 'Cote D"Ivoire' },
  { value: 'Croatia', label: 'Croatia' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Cyprus', label: 'Cyprus' },
  { value: 'Czech Republic', label: 'Czech Republic' },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'Djibouti', label: 'Djibouti' },
  { value: 'Dominica', label: 'Dominica' },
  { value: 'Dominican Republic', label: 'Dominican Republic' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
  { value: 'Eritrea', label: 'Eritrea' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Ethiopia', label: 'Ethiopia' },
  { value: 'Falkland Islands (Malvinas)', label: 'Falkland Islands (Malvinas)' },
  { value: 'Faroe Islands', label: 'Faroe Islands' },
  { value: 'Fiji', label: 'Fiji' },
  { value: 'Finland', label: 'Finland' },
  { value: 'France', label: 'France' },
  { value: 'French Guiana', label: 'French Guiana' },
  { value: 'French Polynesia', label: 'French Polynesia' },
  { value: 'French Southern Territories', label: 'French Southern Territories' },
  { value: 'Gabon', label: 'Gabon' },
  { value: 'Gambia', label: 'Gambia' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Ghana', label: 'Ghana' },
  { value: 'Gibraltar', label: 'Gibraltar' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Greenland', label: 'Greenland' },
  { value: 'Grenada', label: 'Grenada' },
  { value: 'Guadeloupe', label: 'Guadeloupe' },
  { value: 'Guam', label: 'Guam' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Guernsey', label: 'Guernsey' },
  { value: 'Guinea', label: 'Guinea' },
  { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'Haiti', label: 'Haiti' },
  { value: 'Heard Island and Mcdonald Islands', label: 'Heard Island and Mcdonald Islands' },
  { value: 'Holy See (Vatican City State)', label: 'Holy See (Vatican City State)' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Hong Kong', label: 'Hong Kong' },
  { value: 'Hungary', label: 'Hungary' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'India', label: 'India' },
  { value: 'Indonesia', label: 'Indonesia' },
  { value: 'Iran, Islamic Republic Of', label: 'Iran, Islamic Republic Of' },
  { value: 'Iraq', label: 'Iraq' },
  { value: 'Ireland', label: 'Ireland' },
  { value: 'Isle of Man', label: 'Isle of Man' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Jersey', label: 'Jersey' },
  { value: 'Jordan', label: 'Jordan' },
  { value: 'Kazakhstan', label: 'Kazakhstan' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'Kiribati', label: 'Kiribati' },
  {
    value: 'Korea, Democratic People"S Republic of',
    label: 'Korea, Democratic People"S Republic of',
  },
  { value: 'Korea, Republic of', label: 'Korea, Republic of' },
  { value: 'Kuwait', label: 'Kuwait' },
  { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
  { value: 'Lao People"S Democratic Republic', label: 'Lao People"S Democratic Republic' },
  { value: 'Latvia', label: 'Latvia' },
  { value: 'Lebanon', label: 'Lebanon' },
  { value: 'Lesotho', label: 'Lesotho' },
  { value: 'Liberia', label: 'Liberia' },
  { value: 'Libyan Arab Jamahiriya', label: 'Libyan Arab Jamahiriya' },
  { value: 'Liechtenstein', label: 'Liechtenstein' },
  { value: 'Lithuania', label: 'Lithuania' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Macao', label: 'Macao' },
  {
    value: 'Macedonia, The Former Yugoslav Republic of',
    label: 'Macedonia, The Former Yugoslav Republic of',
  },
  { value: 'Madagascar', label: 'Madagascar' },
  { value: 'Malawi', label: 'Malawi' },
  { value: 'Malaysia', label: 'Malaysia' },
  { value: 'Maldives', label: 'Maldives' },
  { value: 'Mali', label: 'Mali' },
  { value: 'Malta', label: 'Malta' },
  { value: 'Marshall Islands', label: 'Marshall Islands' },
  { value: 'Martinique', label: 'Martinique' },
  { value: 'Mauritania', label: 'Mauritania' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Mayotte', label: 'Mayotte' },
  { value: 'Mexico', label: 'Mexico' },
  { value: 'Micronesia, Federated States of', label: 'Micronesia, Federated States of' },
  { value: 'Moldova, Republic of', label: 'Moldova, Republic of' },
  { value: 'Monaco', label: 'Monaco' },
  { value: 'Mongolia', label: 'Mongolia' },
  { value: 'Montenegro', label: 'Montenegro' },
  { value: 'Montserrat', label: 'Montserrat' },
  { value: 'Morocco', label: 'Morocco' },
  { value: 'Mozambique', label: 'Mozambique' },
  { value: 'Myanmar', label: 'Myanmar' },
  { value: 'Namibia', label: 'Namibia' },
  { value: 'Nauru', label: 'Nauru' },
  { value: 'Nepal', label: 'Nepal' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'Netherlands Antilles', label: 'Netherlands Antilles' },
  { value: 'New Caledonia', label: 'New Caledonia' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Niger', label: 'Niger' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'Niue', label: 'Niue' },
  { value: 'Norfolk Island', label: 'Norfolk Island' },
  { value: 'Northern Mariana Islands', label: 'Northern Mariana Islands' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Oman', label: 'Oman' },
  { value: 'Pakistan', label: 'Pakistan' },
  { value: 'Palau', label: 'Palau' },
  { value: 'Palestinian Territory, Occupied', label: 'Palestinian Territory, Occupied' },
  { value: 'Panama', label: 'Panama' },
  { value: 'Papua New Guinea', label: 'Papua New Guinea' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Peru', label: 'Peru' },
  { value: 'Philippines', label: 'Philippines' },
  { value: 'Pitcairn', label: 'Pitcairn' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Puerto Rico', label: 'Puerto Rico' },
  { value: 'Qatar', label: 'Qatar' },
  { value: 'Reunion', label: 'Reunion' },
  { value: 'Romania', label: 'Romania' },
  { value: 'Russian Federation', label: 'Russian Federation' },
  { value: 'RWANDA', label: 'RWANDA' },
  { value: 'Saint Helena', label: 'Saint Helena' },
  { value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
  { value: 'Saint Lucia', label: 'Saint Lucia' },
  { value: 'Saint Pierre and Miquelon', label: 'Saint Pierre and Miquelon' },
  { value: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines' },
  { value: 'Samoa', label: 'Samoa' },
  { value: 'San Marino', label: 'San Marino' },
  { value: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Senegal', label: 'Senegal' },
  { value: 'Serbia', label: 'Serbia' },
  { value: 'Seychelles', label: 'Seychelles' },
  { value: 'Sierra Leone', label: 'Sierra Leone' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Slovakia', label: 'Slovakia' },
  { value: 'Slovenia', label: 'Slovenia' },
  { value: 'Solomon Islands', label: 'Solomon Islands' },
  { value: 'Somalia', label: 'Somalia' },
  { value: 'South Africa', label: 'South Africa' },
  {
    value: 'South Georgia and the South Sandwich Islands',
    label: 'South Georgia and the South Sandwich Islands',
  },
  { value: 'Spain', label: 'Spain' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Sudan', label: 'Sudan' },
  { value: 'Suriname', label: 'Suriname' },
  { value: 'Svalbard and Jan Mayen', label: 'Svalbard and Jan Mayen' },
  { value: 'Swaziland', label: 'Swaziland' },
  { value: 'Sweden', label: 'Sweden' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'Syrian Arab Republic', label: 'Syrian Arab Republic' },
  { value: 'Taiwan, Province of China', label: 'Taiwan, Province of China' },
  { value: 'Tajikistan', label: 'Tajikistan' },
  { value: 'Tanzania, United Republic of', label: 'Tanzania, United Republic of' },
  { value: 'Thailand', label: 'Thailand' },
  { value: 'Timor-Leste', label: 'Timor-Leste' },
  { value: 'Togo', label: 'Togo' },
  { value: 'Tokelau', label: 'Tokelau' },
  { value: 'Tonga', label: 'Tonga' },
  { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
  { value: 'Tunisia', label: 'Tunisia' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'Turkmenistan', label: 'Turkmenistan' },
  { value: 'Turks and Caicos Islands', label: 'Turks and Caicos Islands' },
  { value: 'Tuvalu', label: 'Tuvalu' },
  { value: 'Uganda', label: 'Uganda' },
  { value: 'Ukraine', label: 'Ukraine' },
  { value: 'United Arab Emirates', label: 'United Arab Emirates' },
  { value: 'United Kingdom', label: 'United Kingdom' },
  { value: 'United States', label: 'United States' },
  { value: 'United States Minor Outlying Islands', label: 'United States Minor Outlying Islands' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Uzbekistan', label: 'Uzbekistan' },
  { value: 'Vanuatu', label: 'Vanuatu' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Viet Nam', label: 'Viet Nam' },
  { value: 'Virgin Islands, British', label: 'Virgin Islands, British' },
  { value: 'Virgin Islands, U.S.', label: 'Virgin Islands, U.S.' },
  { value: 'Wallis and Futuna', label: 'Wallis and Futuna' },
  { value: 'Western Sahara', label: 'Western Sahara' },
  { value: 'Yemen', label: 'Yemen' },
  { value: 'Zambia', label: 'Zambia' },
  { value: 'Zimbabwe', label: 'Zimbabwe' },
];

export const STUDY_LEVELS = [
  { value: 'High School', label: 'High School' },
  { value: 'Associate Degree', label: 'Associate Degree' },
  { value: 'Undergraduate', label: 'Undergraduate' },
  { value: 'Bachelor', label: 'Bachelor' },
  { value: 'Master', label: 'Master' },
  { value: 'PhD', label: 'PhD' },
  { value: 'Postdoctoral', label: 'Postdoctoral' },
  { value: 'Certificate', label: 'Certificate' },
  { value: 'Diploma', label: 'Diploma' },
  { value: 'Other', label: 'Other' },
];

export const SCHOLARSHIP_TYPES = [
  { value: 'Scholarship', label: 'scholarship' },
  { value: 'Research Lab', label: 'researchLab' },
];

export const ORGANIZATION_TYPES = [
  { value: 'University', label: 'University' },
  { value: 'College', label: 'College' },
  { value: 'Foundation', label: 'Foundation' },
  { value: 'Non-Profit Organization', label: 'Non-Profit Organization' },
  { value: 'Government Agency', label: 'Government Agency' },
  { value: 'Corporation', label: 'Corporation' },
  { value: 'Research Institute', label: 'Research Institute' },
  { value: 'Other', label: 'Other' },
];

export const GENDER_OPTIONS = [
  { value: 'Male', label: 'Male' },
  { value: 'Female', label: 'Female' },
  { value: 'Other', label: 'Other' },
];

export const MAJOR_CATEGORIES = [
  {
    value: 'Agriculture, Outdoor, and Construction',
    label: 'Agriculture, Outdoor, and Construction',
  },
  { value: 'Art', label: 'Art' },
  { value: ' Business', label: 'Business' },
  { value: 'Education', label: 'Education' },
  { value: 'Health', label: 'Health' },
  { value: 'Humanities', label: 'Humanities' },
  { value: 'Law and Politics', label: 'Law and Politics' },
  { value: 'Social Science', label: 'Social Science' },
  { value: 'STEM', label: 'STEM' },
  { value: 'Other', label: 'Other' },
];

export const MAJOR_NAMES = [
  { value: 'Aeronautics', label: 'Aeronautics' },
  { value: 'Agricultural Business & Technology', label: 'Agricultural Business & Technology' },
  { value: 'Agriculture', label: 'Agriculture' },
  { value: 'Agricultural Economics', label: 'Agricultural Economics' },
  { value: 'Agricultural Operations', label: 'Agricultural Operations' },
  { value: 'Animal Sciences', label: 'Animal Sciences' },
  { value: 'Construction Engineering Technology', label: 'Construction Engineering Technology' },
  { value: 'Construction Management', label: 'Construction Management' },
  {
    value: 'Fish and Wildlands Science and Management',
    label: 'Fish and Wildlands Science and Management',
  },
  { value: 'Food Science', label: 'Food Science' },
  { value: 'Animation', label: 'Animation' },
  { value: 'Art', label: 'Art' },
  { value: 'Art History', label: 'Art History' },
  { value: 'Cinematography', label: 'Cinematography' },
  { value: 'Dance', label: 'Dance' },
  { value: 'Digital Arts', label: 'Digital Arts' },
  { value: 'Drama', label: 'Drama' },
  { value: 'Fashion Design', label: 'Fashion Design' },
  { value: 'Film', label: 'Film' },
  { value: 'Game Design', label: 'Game Design' },
  { value: 'Graphic Design', label: 'Graphic Design' },
  { value: 'Industrial Design', label: 'Industrial Design' },
  { value: 'Illustration', label: 'Illustration' },
  { value: 'Interior Design', label: 'Interior Design' },
  { value: 'Multimedia', label: 'Multimedia' },
  { value: 'Music', label: 'Music' },
  { value: 'Music Management', label: 'Music Management' },
  { value: 'Music Performance', label: 'Music Performance' },
  { value: 'Photography', label: 'Photography' },
  { value: 'Studio Art', label: 'Studio Art' },
  { value: 'Visual and Performing Arts', label: 'Visual and Performing Arts' },
  { value: 'Visual Design', label: 'Visual Design' },
  { value: 'Accounting', label: 'Accounting' },
  { value: 'Actuarial Science', label: 'Actuarial Science' },
  { value: 'Advertising', label: 'Advertising' },
  { value: 'Business', label: 'Business' },
  { value: 'Business Administration', label: 'Business Administration' },
  {
    value: 'Business, Management, and Related Support Services',
    label: 'Business, Management, and Related Support Services',
  },
  { value: 'Econometrics', label: 'Econometrics' },
  { value: 'Economics', label: 'Economics' },
  { value: 'Entrepreneurship', label: 'Entrepreneurship' },
  { value: 'Fashion Merchandising', label: 'Fashion Merchandising' },
  { value: 'Finance', label: 'Finance' },
  { value: 'Human Resources Management', label: 'Human Resources Management' },
  { value: 'International Business', label: 'International Business' },
  { value: 'Insurance', label: 'Insurance' },
  { value: 'Management', label: 'Management' },
  { value: 'Management Information Systems', label: 'Management Information Systems' },
  { value: 'Management Science', label: 'Management Science' },
  { value: 'Managerial Economics', label: 'Managerial Economics' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Operations Management', label: 'Operations Management' },
  { value: 'Organizational Behavior', label: 'Organizational Behavior' },
  { value: 'Real Estate', label: 'Real Estate' },
  { value: 'Sales', label: 'Sales' },
  { value: 'Supply Chain Management', label: 'Supply Chain Management' },
  { value: 'Early Childhood Education', label: 'Early Childhood Education' },
  { value: 'Education', label: 'Education' },
  { value: 'Education (Other)', label: 'Education (Other)' },
  { value: 'Elementary Education', label: 'Elementary Education' },
  { value: 'Health and Physical Education', label: 'Health and Physical Education' },
  { value: 'Language Arts Teacher Education', label: 'Language Arts Teacher Education' },
  { value: 'Mathematics Teacher Education', label: 'Mathematics Teacher Education' },
  { value: 'Middle School Education', label: 'Middle School Education' },
  { value: 'Music Teacher Education', label: 'Music Teacher Education' },
  {
    value: 'Physical Education Teaching and Coaching',
    label: 'Physical Education Teaching and Coaching',
  },
  { value: 'Secondary Education', label: 'Secondary Education' },
  { value: 'Special Education', label: 'Special Education' },
  { value: 'Teacher Education', label: 'Teacher Education' },
  { value: 'Athletic Training', label: 'Athletic Training' },
  { value: 'Audiology', label: 'Audiology' },
  { value: 'Clinical Laboratory Science', label: 'Clinical Laboratory Science' },
  { value: 'Cognitive Science', label: 'Cognitive Science' },
  { value: 'Communication Sciences', label: 'Communication Sciences' },
  { value: 'Community Health', label: 'Community Health' },
  { value: 'Community Health Services', label: 'Community Health Services' },
  { value: 'Dental Hygiene', label: 'Dental Hygiene' },
  { value: 'Health and Wellness', label: 'Health and Wellness' },
  { value: 'Health Care Administration', label: 'Health Care Administration' },
  { value: 'Health Information', label: 'Health Information' },
  { value: 'Health/Medical Preparatory Programs', label: 'Health/Medical Preparatory Programs' },
  {
    value: 'Health Professions and Related Clinical Sciences',
    label: 'Health Professions and Related Clinical Sciences',
  },
  { value: 'Health Services', label: 'Health Services' },
  {
    value: 'Hospital and Health Care Facilities Administration',
    label: 'Hospital and Health Care Facilities Administration',
  },
  { value: 'Medical Radiologic Technology', label: 'Medical Radiologic Technology' },
  { value: 'Nursing', label: 'Nursing' },
  { value: 'Nursing Research', label: 'Nursing Research' },
  { value: 'Nursing Science', label: 'Nursing Science' },
  { value: 'Nutrition', label: 'Nutrition' },
  { value: 'Nutrition Sciences', label: 'Nutrition Sciences' },
  { value: 'Public Health', label: 'Public Health' },
  { value: 'Public Health Education', label: 'Public Health Education' },
  { value: 'Radiologic Technology', label: 'Radiologic Technology' },
  { value: 'Respiratory Care Therapy', label: 'Respiratory Care Therapy' },
  { value: 'Speech-Language Pathology', label: 'Speech-Language Pathology' },
  { value: 'Applied Communication', label: 'Applied Communication' },
  { value: 'Biblical Studies', label: 'Biblical Studies' },
  { value: 'Communication', label: 'Communication' },
  { value: 'Communication and Media Studies', label: 'Communication and Media Studies' },
  { value: 'Creative Writing', label: 'Creative Writing' },
  { value: 'Digital Communication and Multimedia', label: 'Digital Communication and Multimedia' },
  { value: 'English', label: 'English' },
  { value: 'Foreign Languages and Literature', label: 'Foreign Languages and Literature' },
  { value: 'French Language and Literature', label: 'French Language and Literature' },
  { value: 'Gender Studies', label: 'Gender Studies' },
  { value: 'General Studies', label: 'General Studies' },
  { value: 'General Studies and Humanities', label: 'General Studies and Humanities' },
  { value: 'History', label: 'History' },
  { value: 'Humanities', label: 'Humanities' },
  { value: 'Journalism', label: 'Journalism' },
  { value: 'Liberal Arts', label: 'Liberal Arts' },
  { value: 'Linguistics', label: 'Linguistics' },
  { value: 'Mass Communication', label: 'Mass Communication' },
  { value: 'Organizational Communication', label: 'Organizational Communication' },
  {
    value: 'Parks, Recreation and Leisure Facilities Management',
    label: 'Parks, Recreation and Leisure Facilities Management',
  },
  {
    value: 'Parks, Recreation and Leisure Studies',
    label: 'Parks, Recreation and Leisure Studies',
  },
  { value: 'Philosophy', label: 'Philosophy' },
  { value: 'Public Relations', label: 'Public Relations' },
  { value: 'Public Relations/Image Management', label: 'Public Relations/Image Management' },
  { value: 'Radio and Television', label: 'Radio and Television' },
  { value: 'Religious Studies', label: 'Religious Studies' },
  { value: 'Rhetoric and Composition', label: 'Rhetoric and Composition' },
  { value: 'Spanish Language and Literature', label: 'Spanish Language and Literature' },
  { value: 'Speech and Rhetoric', label: 'Speech and Rhetoric' },
  { value: 'Talmudic Studies', label: 'Talmudic Studies' },
  { value: 'Theology', label: 'Theology' },
  { value: 'Community Organization and Advocacy', label: 'Community Organization and Advocacy' },
  { value: 'Geography', label: 'Geography' },
  { value: 'International Relations', label: 'International Relations' },
  { value: 'International Studies', label: 'International Studies' },
  { value: 'Legal Assistant', label: 'Legal Assistant' },
  { value: 'Legal Studies', label: 'Legal Studies' },
  { value: 'Political Science', label: 'Political Science' },
  { value: 'Public Administration', label: 'Public Administration' },
  { value: 'Public Policy Analysis', label: 'Public Policy Analysis' },
  { value: 'Social Work', label: 'Social Work' },
  { value: 'Sociology', label: 'Sociology' },
  { value: 'Anthropology', label: 'Anthropology' },
  { value: 'Behavioral Sciences', label: 'Behavioral Sciences' },
  { value: 'Child Development', label: 'Child Development' },
  { value: 'Criminology', label: 'Criminology' },
  { value: 'Experimental Psychology', label: 'Experimental Psychology' },
  { value: 'Human Development and Family Studies', label: 'Human Development and Family Studies' },
  { value: 'Psychology', label: 'Psychology' },
  { value: 'Aerospace Engineering', label: 'Aerospace Engineering' },
  { value: 'Applied Mathematics', label: 'Applied Mathematics' },
  { value: 'Architecture', label: 'Architecture' },
  { value: 'Astrophysics', label: 'Astrophysics' },
  { value: 'Biochemistry', label: 'Biochemistry' },
  { value: 'Biological and Biomedical Sciences', label: 'Biological and Biomedical Sciences' },
  { value: 'Biological and Physical Sciences', label: 'Biological and Physical Sciences' },
  { value: 'Biology', label: 'Biology' },
  { value: 'Biomedical Engineering', label: 'Biomedical Engineering' },
  { value: 'Biomedical Sciences', label: 'Biomedical Sciences' },
  { value: 'Cellular and Molecular Biology', label: 'Cellular and Molecular Biology' },
  { value: 'Chemical Engineering', label: 'Chemical Engineering' },
  { value: 'Chemistry', label: 'Chemistry' },
  { value: 'Civil Engineering', label: 'Civil Engineering' },
  { value: 'Computer Engineering', label: 'Computer Engineering' },
  { value: 'Computer and Information Sciences', label: 'Computer and Information Sciences' },
  { value: 'Computer Science', label: 'Computer Science' },
  { value: 'Computer Software Engineering', label: 'Computer Software Engineering' },
  { value: 'Computer Systems Networking', label: 'Computer Systems Networking' },
  { value: 'Conservation', label: 'Conservation' },
  { value: 'Earth Science', label: 'Earth Science' },
  { value: 'Electrical Engineering', label: 'Electrical Engineering' },
  { value: 'Engineering', label: 'Engineering' },
  { value: 'Environmental Science', label: 'Environmental Science' },
  { value: 'Environmental Studies', label: 'Environmental Studies' },
  { value: 'Exercise Physiology', label: 'Exercise Physiology' },
  { value: 'Informatics', label: 'Informatics' },
  { value: 'Information Science', label: 'Information Science' },
  { value: 'Information Systems Security', label: 'Information Systems Security' },
  { value: 'Information Technology (IT)', label: 'Information Technology (IT)' },
  { value: 'Kinesiology', label: 'Kinesiology' },
  { value: 'Marine Biology', label: 'Marine Biology' },
  { value: 'Mathematics', label: 'Mathematics' },
  { value: 'Mechanical Engineering', label: 'Mechanical Engineering' },
  { value: 'Microbiology', label: 'Microbiology' },
  { value: 'Neuroscience', label: 'Neuroscience' },
  { value: 'Petroleum Engineering', label: 'Petroleum Engineering' },
  { value: 'Physics', label: 'Physics' },
  {
    value: 'Physiology, Pathology, and Related Sciences, Other',
    label: 'Physiology, Pathology, and Related Sciences, Other',
  },
  { value: 'Statistics', label: 'Statistics' },
  { value: 'Web Design', label: 'Web Design' },
  { value: 'Zoology', label: 'Zoology' },
  { value: 'Apparel and Textiles', label: 'Apparel and Textiles' },
  { value: 'Corrections and Criminal Justice', label: 'Corrections and Criminal Justice' },
  { value: 'Criminal Justice', label: 'Criminal Justice' },
  { value: 'Electromechanical Technology', label: 'Electromechanical Technology' },
  {
    value: 'Foods, Nutrition, and Wellness Studies',
    label: 'Foods, Nutrition, and Wellness Studies',
  },
  { value: 'Forensic Science and Technology', label: 'Forensic Science and Technology' },
  { value: 'Hospitality Administration', label: 'Hospitality Administration' },
  { value: 'Hotel Management', label: 'Hotel Management' },
  { value: 'Human Sciences (General)', label: 'Human Sciences (General)' },
  { value: 'Human Services', label: 'Human Services' },
  { value: 'Law Enforcement Administration', label: 'Law Enforcement Administration' },
  { value: 'Police Science', label: 'Police Science' },
  { value: 'Sport and Fitness Administration', label: 'Sport and Fitness Administration' },
  { value: 'Other', label: 'Other' },
];

export const NOTIFICATION_TYPES = {
  SCHOLARSHIP: 'scholarship',
  SCHOLARSHIP_UPDATED: 'scholarshipUpdated',
  SCHOLARSHIP_NEWS: 'scholarshipNews',
  APPLICATION: 'application',
  SCHOLARSHIP_APPLICATION: 'scholarshipApplication',
  APPLICATION_REFERRAL: 'applicationReferral',
};

export const RELIGIONS = [
  {
    value: 'Buddhism',
    label: 'Buddhism',
  },
  {
    value: 'Christianity',
    label: 'Christianity',
  },
  {
    value: 'Islam',
    label: 'Islam',
  },
  {
    value: 'Hinduism',
    label: 'Hinduism',
  },
  {
    value: 'Judaism',
    label: 'Judaism',
  },
  {
    value: 'Sikhism',
    label: 'Sikhism',
  },
  {
    value: 'Taoism',
    label: 'Taoism',
  },
  {
    value: 'Confucianism',
    label: 'Confucianism',
  },
  {
    value: 'Shinto',
    label: 'Shinto',
  },
  {
    value: 'Jainism',
    label: 'Jainism',
  },
  {
    value: "Bahá'í Faith",
    label: "Bahá'í Faith",
  },
  {
    value: 'Zoroastrianism',
    label: 'Zoroastrianism',
  },
  {
    value: 'Agnostic',
    label: 'Agnostic',
  },
  {
    value: 'Atheist',
    label: 'Atheist',
  },
  {
    value: 'Spiritual but not religious',
    label: 'Spiritual but not religious',
  },
  {
    value: 'Other',
    label: 'Other',
  },
  {
    value: 'None',
    label: 'No religion',
  },
];

export const ETHNICITIES = [
  {
    value: 'Asian',
    label: 'Asian',
  },
  {
    value: 'Black or African American',
    label: 'Black or African American',
  },
  {
    value: 'Hispanic or Latino',
    label: 'Hispanic or Latino',
  },
  {
    value: 'Native American or Alaska Native',
    label: 'Native American or Alaska Native',
  },
  {
    value: 'Native Hawaiian or Other Pacific Islander',
    label: 'Native Hawaiian or Other Pacific Islander',
  },
  {
    value: 'White or Caucasian',
    label: 'White or Caucasian',
  },
  {
    value: 'Mixed Race',
    label: 'Mixed Race',
  },
  {
    value: 'Middle Eastern',
    label: 'Middle Eastern',
  },
  {
    value: 'South Asian',
    label: 'South Asian',
  },
  {
    value: 'Southeast Asian',
    label: 'Southeast Asian',
  },
  {
    value: 'East Asian',
    label: 'East Asian',
  },
  {
    value: 'Other',
    label: 'Other',
  },
  {
    value: 'Prefer not to say',
    label: 'Prefer not to say',
  },
];

export const RACES = [
  {
    value: 'American Indian or Alaska Native',
    label: 'American Indian or Alaska Native',
  },
  {
    value: 'Asian',
    label: 'Asian',
  },
  {
    value: 'Black or African American',
    label: 'Black or African American',
  },
  {
    value: 'Hispanic or Latino',
    label: 'Hispanic or Latino',
  },
  {
    value: 'Native Hawaiian or Other Pacific Islander',
    label: 'Native Hawaiian or Other Pacific Islander',
  },
  {
    value: 'White',
    label: 'White',
  },
  {
    value: 'Two or More Races',
    label: 'Two or More Races',
  },
  {
    value: 'Other',
    label: 'Other',
  },
  {
    value: 'Prefer not to say',
    label: 'Prefer not to say',
  },
];

export const CITIZENSHIP_STATUS = [
  {
    value: 'Citizen',
    label: 'Citizen',
  },
  {
    value: 'Permanent Resident',
    label: 'Permanent Resident',
  },
  {
    value: 'Temporary Resident',
    label: 'Temporary Resident',
  },
  {
    value: 'Student Visa',
    label: 'Student Visa',
  },
  {
    value: 'Work Visa',
    label: 'Work Visa',
  },
  {
    value: 'Refugee',
    label: 'Refugee',
  },
  {
    value: 'Asylee',
    label: 'Asylee',
  },
  {
    value: 'DACA Recipient',
    label: 'DACA Recipient',
  },
  {
    value: 'Undocumented',
    label: 'Undocumented',
  },
  {
    value: 'Other',
    label: 'Other',
  },
  {
    value: 'Prefer not to say',
    label: 'Prefer not to say',
  },
];
