import { IApplication, ICaseStudy, INews, IProviderProfile, IScholarship } from '@/lib/schemas';

export const DEFAULT_SCHOLARSHIP_FORM_VALUES: IScholarship = {
  id: undefined,
  title: '',
  slug: '',
  shortDescription: '',
  description: '',
  requirements: '',
  benefits: '',
  fields: '',
  country: '',
  university: '',
  studyLevel: '',
  scholarshipType: '',
  fundingAmount: '',
  startDate: new Date().getTime(),
  endDate: new Date().getTime(),
  availableSlots: undefined,
  languageRequirement: '',
  gpaRequirement: undefined,
  requiredMajor: '',
  genderRequirement: '',
  restrictedNationalities: '',
  minAge: undefined,
  maxAge: undefined,
  requiredSatScore: undefined,
  requiredActScore: undefined,
  requiredGreScore: undefined,
  requiredToeflScore: undefined,
  requiredIeltsScore: undefined,
  requiredWorkExperienceYears: 0,
  requiredPublicationCount: 0,
  requiredAcademicAwards: '',
  requiredClassRankPercentile: undefined,
  scholarshipPreferences: [],
};

export const DEFAULT_APPLICATION_FORM_VALUES: IApplication = {
  id: undefined,
  applicationName: 'Application',
  code: '',
  versionApplication: 1,
  fullName: '',
  gender: '',
  dateOfBirth: '',
  email: '',
  phone: '',
  address: '',
  nationality: '',
  educationLevel: '',
  schoolName: '',
  major: '',
  gpa: 0,
  graduationYear: '',
  skills: '',
  achievements: '',
  extracurricular: '',
  motivation: '',
  personalStatement: '',
  languages: '',
  careerGoal: '',
  researchInterest: '',
  academicAwards: '',
  publicationCount: undefined,
  satScore: undefined,
  actScore: undefined,
  greScore: undefined,
  gmatScore: undefined,
  toeflScore: undefined,
  ieltsScore: undefined,
  workExperienceYears: undefined,
  classRank: undefined,
  classSize: undefined,
  classRankPercentile: undefined,
  age: undefined,
  citizenship: '',
  isAthlete: false,
  athleticAchievements: '',
  applicationAttributes: [],
};

export const DEFAULT_PROVIDER_FORM_VALUES: IProviderProfile = {
  providerProfile: {
    organizationName: '',
    organizationType: '',
    website: '',
    email: '',
    phone: '',
    addressSummary: '',
    description: '',
    yearEstablished: undefined,
    accreditation: '',
    specialization: '',
    verified: false,
    country: '',
    providerContactDtos: [],
  },
};

export const DEFAULT_NEWS_FORM_VALUES: INews = {
  id: undefined,
  title: '',
  content: '',
  scholarshipId: undefined,
};

export const DEFAULT_CASE_STUDY_FORM_VALUES: ICaseStudy = {
  scholarshipId: undefined as any,
  title: '',
  verified: false,
  initialThoughts: '',
  preparationProcess: '',
  challenges: '',
  victoryMoment: '',
  advice: '',
};
