import { Target, Shield, Zap, BookOpen, Heart, Globe, Users, Search, Award } from 'lucide-react';

// Features data
export const featuresData = [
  {
    icon: Target,
    title: 'Smart Matching',
    description:
      'AI-powered algorithm matches you with scholarships that fit your profile perfectly.',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    icon: Shield,
    title: 'Verified Opportunities',
    description: 'Every scholarship is verified and vetted to ensure legitimacy and quality.',
    color: 'from-emerald-500 to-teal-500',
  },
  {
    icon: Zap,
    title: 'Instant Applications',
    description: 'Apply to multiple scholarships with one click using our streamlined process.',
    color: 'from-violet-500 to-purple-500',
  },
  {
    icon: BookOpen,
    title: 'Expert Guidance',
    description: 'Access resources and tips from scholarship experts to improve your chances.',
    color: 'from-orange-500 to-red-500',
  },
  {
    icon: Heart,
    title: 'Personalized Dashboard',
    description: 'Track your applications, deadlines, and progress all in one place.',
    color: 'from-pink-500 to-rose-500',
  },
  {
    icon: Globe,
    title: 'Global Network',
    description: 'Access scholarships from universities and organizations worldwide.',
    color: 'from-indigo-500 to-blue-500',
  },
];

// How It Works steps
export const howItWorksSteps = [
  {
    step: '01',
    title: 'Create Your Profile',
    description: 'Share your academic background, interests, and goals. Takes less than 5 minutes.',
    icon: Users,
  },
  {
    step: '02',
    title: 'Get Matched',
    description: 'Our AI analyzes thousands of scholarships and presents the best matches for you.',
    icon: Search,
  },
  {
    step: '03',
    title: 'Apply & Win',
    description: 'Submit applications with one click and track your progress until you win.',
    icon: Award,
  },
];

// Mock Scholarship data (for development/testing)
export const mockScholarshipOpportunities: Scholarship[] = [
  {
    id: 10,
    providerId: 2,
    title: 'Fullbright Scholarship 2025',
    slug: 'fullbright-scholarship-2025',
    shortDescription: 'Học bổng toàn phần cho sinh viên quốc tế năm 2025.',
    description:
      'Học bổng Fullbright 2025 hỗ trợ sinh viên có thành tích học tập xuất sắc theo học tại các trường đại học hàng đầu thế giới.',
    requirements: 'GPA từ 3.5 trở lên, IELTS 7.0, thư giới thiệu và bài luận cá nhân.',
    benefits: 'Toàn bộ học phí, sinh hoạt phí và vé máy bay khứ hồi.',
    fields: 'Khoa học máy tính, Kinh tế, Kỹ thuật',
    country: 'United States',
    university: 'Harvard University',
    studyLevel: 'Master',
    scholarshipType: 'Full',
    fundingAmount: '100000 USD',
    startDate: 1766960133891,
    endDate: 1769638533891,
    availableSlots: 10,
    languageRequirement: 'IELTS 7.0 hoặc TOEFL 95',
    gpaRequirement: 3.5,
    scholarshipMedias: [
      {
        id: 12,
        s3Key: 'public/scholarship/10/',
        size: 0,
        folderName: 'scholarship/10',
        fileName: '',
        isPublic: true,
        url: 'https://edumatch.s3.ap-southeast-1.amazonaws.com/public/scholarship/10/',
      },
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=400&fit=crop&auto=format',
    ],
  },
  {
    id: 1,
    providerId: 1,
    title: 'Global Leaders Scholarship',
    slug: 'global-leaders-scholarship',
    shortDescription: 'Scholarship for future global leaders.',
    description:
      'This scholarship is designed for students who demonstrate outstanding leadership potential and academic excellence. We support ambitious students who want to make a difference in the world.',
    requirements:
      'Open to undergraduate students with leadership experience and a minimum GPA of 3.5.',
    benefits: 'Full tuition coverage, mentorship program, networking opportunities',
    fields: 'Business Administration, International Relations, Public Policy',
    country: 'United States',
    university: 'Harvard University',
    studyLevel: 'Bachelor',
    scholarshipType: 'Full',
    fundingAmount: '15000 USD',
    startDate: new Date('2025-09-01').getTime(),
    endDate: new Date('2025-12-31').getTime(),
    availableSlots: 10,
    languageRequirement: 'IELTS 7.0 or TOEFL 100',
    gpaRequirement: 3.5,
    scholarshipMedias: [
      {
        id: 1,
        s3Key: 'public/scholarship/1/image1.jpg',
        size: 102400,
        folderName: 'scholarship/1',
        fileName: 'image1.jpg',
        isPublic: true,
        url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
      },
      {
        id: 2,
        s3Key: 'public/scholarship/1/image2.jpg',
        size: 98304,
        folderName: 'scholarship/1',
        fileName: 'image2.jpg',
        isPublic: true,
        url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
      },
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1529390079861-591de354faf5?w=800&h=400&fit=crop&auto=format',
    ],
  },
  {
    id: 2,
    providerId: 2,
    title: 'STEM Excellence Award',
    slug: 'stem-excellence-award',
    shortDescription: 'Funding support for top STEM students.',
    description:
      'The STEM Excellence Award supports students in Science, Technology, Engineering, and Mathematics disciplines. We provide comprehensive support for innovative research projects.',
    requirements:
      'Available to both undergraduate and graduate students pursuing STEM fields with GPA 3.2 or higher.',
    benefits: 'Research funding, lab access, conference attendance',
    fields: 'Engineering, Computer Science, Mathematics, Physics',
    country: 'United Kingdom',
    university: 'University of Cambridge',
    studyLevel: 'Master',
    scholarshipType: 'Partial',
    fundingAmount: '12000 USD',
    startDate: new Date('2025-08-15').getTime(),
    endDate: new Date('2025-10-15').getTime(),
    availableSlots: 15,
    languageRequirement: 'IELTS 6.5 or TOEFL 90',
    gpaRequirement: 3.2,
    scholarshipMedias: [],
    imageUrls: [
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop&auto=format',
    ],
  },
  {
    id: 3,
    providerId: 3,
    title: 'International Arts Fellowship',
    slug: 'international-arts-fellowship',
    shortDescription: 'A fellowship for talented international artists.',
    description:
      'Supports international students in fine arts, performing arts, and design with mentorship and funding.',
    requirements: 'Open to international students applying for arts-related programs.',
    benefits: 'Studio space, exhibition opportunities, artist mentorship',
    fields: 'Fine Arts, Performing Arts, Design, Creative Writing',
    country: 'Canada',
    university: 'University of Toronto',
    studyLevel: 'Bachelor',
    scholarshipType: 'Partial',
    fundingAmount: '8000 USD',
    startDate: new Date('2025-09-01').getTime(),
    endDate: new Date('2025-11-20').getTime(),
    availableSlots: 8,
    languageRequirement: 'IELTS 6.0 or TOEFL 80',
    gpaRequirement: 2.8,
    scholarshipMedias: [],
  },
  {
    id: 4,
    providerId: 4,
    title: 'Medical Research Grant',
    slug: 'medical-research-grant',
    shortDescription: 'Grant for outstanding medical researchers.',
    description:
      'Provides funding for students and young researchers focusing on innovative healthcare solutions.',
    requirements:
      'Graduate students or postgraduates with strong academic background in medicine or biomedical sciences.',
    benefits: 'Research equipment, publication support, clinical rotations',
    fields: 'Medicine, Biomedical Science, Public Health',
    country: 'Germany',
    university: 'Heidelberg University',
    studyLevel: 'PhD',
    scholarshipType: 'Full',
    fundingAmount: '20000 USD',
    startDate: new Date('2025-10-01').getTime(),
    endDate: new Date('2026-01-05').getTime(),
    availableSlots: 5,
    languageRequirement: 'IELTS 7.5 or TOEFL 110',
    gpaRequirement: 3.7,
    scholarshipMedias: [],
  },
  {
    id: 5,
    providerId: 5,
    title: 'Sustainable Development Scholarship',
    slug: 'sustainable-development-scholarship',
    shortDescription: 'Scholarship for students passionate about sustainability.',
    description:
      'Aims to support students researching renewable energy, environmental policy, and sustainable practices.',
    requirements:
      'Students enrolled in sustainability or environmental-related programs worldwide.',
    benefits: 'Field research funding, sustainability conference attendance',
    fields: 'Environmental Science, Sustainability, Renewable Energy',
    country: 'Australia',
    university: 'University of Melbourne',
    studyLevel: 'Master',
    scholarshipType: 'Partial',
    fundingAmount: '10000 USD',
    startDate: new Date('2025-08-01').getTime(),
    endDate: new Date('2025-09-30').getTime(),
    availableSlots: 12,
    languageRequirement: 'IELTS 6.5 or TOEFL 90',
    gpaRequirement: 3.0,
    scholarshipMedias: [],
    imageUrls: [
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&h=400&fit=crop&auto=format',
    ],
  },
];
