import { Target, Shield, Zap, BookOpen, Heart, Globe, Users, Search, Award } from 'lucide-react';

// Features data
export const featuresData = [
  {
    icon: Target,
    title: 'Smart Matching',
    description:
      'AI-powered algorithm matches you with scholarships that fit your profile perfectly.',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    icon: Shield,
    title: 'Verified Opportunities',
    description: 'Every scholarship is verified and vetted to ensure legitimacy and quality.',
    color: 'from-emerald-500 to-teal-500',
  },
  {
    icon: Zap,
    title: 'Instant Applications',
    description: 'Apply to multiple scholarships with one click using our streamlined process.',
    color: 'from-violet-500 to-purple-500',
  },
  {
    icon: BookOpen,
    title: 'Expert Guidance',
    description: 'Access resources and tips from scholarship experts to improve your chances.',
    color: 'from-orange-500 to-red-500',
  },
  {
    icon: Heart,
    title: 'Personalized Dashboard',
    description: 'Track your applications, deadlines, and progress all in one place.',
    color: 'from-pink-500 to-rose-500',
  },
  {
    icon: Globe,
    title: 'Global Network',
    description: 'Access scholarships from universities and organizations worldwide.',
    color: 'from-indigo-500 to-blue-500',
  },
];

// How It Works steps
export const howItWorksSteps = [
  {
    step: '01',
    title: 'Create Your Profile',
    description: 'Share your academic background, interests, and goals. Takes less than 5 minutes.',
    icon: Users,
  },
  {
    step: '02',
    title: 'Get Matched',
    description: 'Our AI analyzes thousands of scholarships and presents the best matches for you.',
    icon: Search,
  },
  {
    step: '03',
    title: 'Apply & Win',
    description: 'Submit applications with one click and track your progress until you win.',
    icon: Award,
  },
];

// Mock Scholarship data (for development/testing)
export const mockScholarshipOpportunities: Scholarship[] = [
  {
    id: 10,
    providerId: 2,
    title: 'Fullbright Scholarship 2025',
    slug: 'fullbright-scholarship-2025',
    shortDescription: 'Học bổng toàn phần cho sinh viên quốc tế năm 2025.',
    description:
      'Học bổng Fullbright 2025 hỗ trợ sinh viên có thành tích học tập xuất sắc theo học tại các trường đại học hàng đầu thế giới.',
    requirements: 'GPA từ 3.5 trở lên, IELTS 7.0, thư giới thiệu và bài luận cá nhân.',
    benefits: 'Toàn bộ học phí, sinh hoạt phí và vé máy bay khứ hồi.',
    fields: 'Khoa học máy tính, Kinh tế, Kỹ thuật',
    country: 'United States',
    university: 'Harvard University',
    studyLevel: 'Master',
    scholarshipType: 'Full',
    fundingAmount: '100000 USD',
    startDate: 1766960133891,
    endDate: 1769638533891,
    availableSlots: 10,
    languageRequirement: 'IELTS 7.0 hoặc TOEFL 95',
    gpaRequirement: 3.5,
    scholarshipMedias: [
      {
        id: 12,
        s3Key: 'public/scholarship/10/',
        size: 0,
        folderName: 'scholarship/10',
        fileName: '',
        isPublic: true,
        url: 'https://edumatch.s3.ap-southeast-1.amazonaws.com/public/scholarship/10/',
      },
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=400&fit=crop&auto=format',
    ],
  },
  {
    id: 1,
    providerId: 1,
    title: 'Global Leaders Scholarship',
    slug: 'global-leaders-scholarship',
    shortDescription: 'Scholarship for future global leaders.',
    description:
      'This scholarship is designed for students who demonstrate outstanding leadership potential and academic excellence. We support ambitious students who want to make a difference in the world.',
    requirements:
      'Open to undergraduate students with leadership experience and a minimum GPA of 3.5.',
    benefits: 'Full tuition coverage, mentorship program, networking opportunities',
    fields: 'Business Administration, International Relations, Public Policy',
    country: 'United States',
    university: 'Harvard University',
    studyLevel: 'Bachelor',
    scholarshipType: 'Full',
    fundingAmount: '15000 USD',
    startDate: new Date('2025-09-01').getTime(),
    endDate: new Date('2025-12-31').getTime(),
    availableSlots: 10,
    languageRequirement: 'IELTS 7.0 or TOEFL 100',
    gpaRequirement: 3.5,
    scholarshipMedias: [
      {
        id: 1,
        s3Key: 'public/scholarship/1/image1.jpg',
        size: 102400,
        folderName: 'scholarship/1',
        fileName: 'image1.jpg',
        isPublic: true,
        url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
      },
      {
        id: 2,
        s3Key: 'public/scholarship/1/image2.jpg',
        size: 98304,
        folderName: 'scholarship/1',
        fileName: 'image2.jpg',
        isPublic: true,
        url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
      },
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1529390079861-591de354faf5?w=800&h=400&fit=crop&auto=format',
    ],
  },
  {
    id: 2,
    providerId: 2,
    title: 'STEM Excellence Award',
    slug: 'stem-excellence-award',
    shortDescription: 'Funding support for top STEM students.',
    description:
      'The STEM Excellence Award supports students in Science, Technology, Engineering, and Mathematics disciplines. We provide comprehensive support for innovative research projects.',
    requirements:
      'Available to both undergraduate and graduate students pursuing STEM fields with GPA 3.2 or higher.',
    benefits: 'Research funding, lab access, conference attendance',
    fields: 'Engineering, Computer Science, Mathematics, Physics',
    country: 'United Kingdom',
    university: 'University of Cambridge',
    studyLevel: 'Master',
    scholarshipType: 'Partial',
    fundingAmount: '12000 USD',
    startDate: new Date('2025-08-15').getTime(),
    endDate: new Date('2025-10-15').getTime(),
    availableSlots: 15,
    languageRequirement: 'IELTS 6.5 or TOEFL 90',
    gpaRequirement: 3.2,
    scholarshipMedias: [],
    imageUrls: [
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop&auto=format',
    ],
  },
  {
    id: 3,
    providerId: 3,
    title: 'International Arts Fellowship',
    slug: 'international-arts-fellowship',
    shortDescription: 'A fellowship for talented international artists.',
    description:
      'Supports international students in fine arts, performing arts, and design with mentorship and funding.',
    requirements: 'Open to international students applying for arts-related programs.',
    benefits: 'Studio space, exhibition opportunities, artist mentorship',
    fields: 'Fine Arts, Performing Arts, Design, Creative Writing',
    country: 'Canada',
    university: 'University of Toronto',
    studyLevel: 'Bachelor',
    scholarshipType: 'Partial',
    fundingAmount: '8000 USD',
    startDate: new Date('2025-09-01').getTime(),
    endDate: new Date('2025-11-20').getTime(),
    availableSlots: 8,
    languageRequirement: 'IELTS 6.0 or TOEFL 80',
    gpaRequirement: 2.8,
    scholarshipMedias: [],
  },
  {
    id: 4,
    providerId: 4,
    title: 'Medical Research Grant',
    slug: 'medical-research-grant',
    shortDescription: 'Grant for outstanding medical researchers.',
    description:
      'Provides funding for students and young researchers focusing on innovative healthcare solutions.',
    requirements:
      'Graduate students or postgraduates with strong academic background in medicine or biomedical sciences.',
    benefits: 'Research equipment, publication support, clinical rotations',
    fields: 'Medicine, Biomedical Science, Public Health',
    country: 'Germany',
    university: 'Heidelberg University',
    studyLevel: 'PhD',
    scholarshipType: 'Full',
    fundingAmount: '20000 USD',
    startDate: new Date('2025-10-01').getTime(),
    endDate: new Date('2026-01-05').getTime(),
    availableSlots: 5,
    languageRequirement: 'IELTS 7.5 or TOEFL 110',
    gpaRequirement: 3.7,
    scholarshipMedias: [],
  },
  {
    id: 5,
    providerId: 5,
    title: 'Sustainable Development Scholarship',
    slug: 'sustainable-development-scholarship',
    shortDescription: 'Scholarship for students passionate about sustainability.',
    description:
      'Aims to support students researching renewable energy, environmental policy, and sustainable practices.',
    requirements:
      'Students enrolled in sustainability or environmental-related programs worldwide.',
    benefits: 'Field research funding, sustainability conference attendance',
    fields: 'Environmental Science, Sustainability, Renewable Energy',
    country: 'Australia',
    university: 'University of Melbourne',
    studyLevel: 'Master',
    scholarshipType: 'Partial',
    fundingAmount: '10000 USD',
    startDate: new Date('2025-08-01').getTime(),
    endDate: new Date('2025-09-30').getTime(),
    availableSlots: 12,
    languageRequirement: 'IELTS 6.5 or TOEFL 90',
    gpaRequirement: 3.0,
    scholarshipMedias: [],
    imageUrls: [
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&h=400&fit=crop&auto=format',
    ],
  },
  {
    id: 21,
    providerId: 6,
    title: 'Technology Innovation Scholarship',
    slug: 'technology-innovation-scholarship',
    shortDescription: 'Supporting the next generation of tech innovators.',
    description:
      'Designed for students pursuing careers in software development, AI, and emerging technologies.',
    requirements: 'Computer Science or related field, GPA 3.3+, portfolio of projects',
    benefits: 'Tuition support, internship opportunities, tech mentorship',
    fields: 'Computer Science, Software Engineering, Artificial Intelligence',
    country: 'Singapore',
    university: 'National University of Singapore',
    studyLevel: 'Bachelor',
    scholarshipType: 'Partial',
    fundingAmount: '25000 USD',
    startDate: new Date('2025-09-15').getTime(),
    endDate: new Date('2025-11-30').getTime(),
    availableSlots: 20,
    languageRequirement: 'IELTS 6.5 or TOEFL 90',
    gpaRequirement: 3.3,
    scholarshipMedias: [],
  },
  {
    id: 22,
    providerId: 7,
    title: 'Women in Engineering Excellence Award',
    slug: 'women-engineering-excellence',
    shortDescription: 'Empowering women in engineering fields.',
    description:
      'Awarded to outstanding female students pursuing engineering degrees to promote gender diversity.',
    requirements: 'Female students in engineering, GPA 3.4+, leadership experience',
    benefits: 'Full tuition, networking events, career mentorship',
    fields: 'Engineering, Mechanical Engineering, Civil Engineering',
    country: 'United Kingdom',
    university: 'Imperial College London',
    studyLevel: 'Master',
    scholarshipType: 'Full',
    fundingAmount: '35000 USD',
    startDate: new Date('2025-08-01').getTime(),
    endDate: new Date('2025-10-15').getTime(),
    availableSlots: 10,
    languageRequirement: 'IELTS 7.0 or TOEFL 100',
    gpaRequirement: 3.4,
    scholarshipMedias: [],
  },
  {
    id: 23,
    providerId: 8,
    title: 'Asia-Pacific Business Leadership Program',
    slug: 'asia-pacific-business-leadership',
    shortDescription: 'Scholarship for future business leaders in Asia-Pacific.',
    description:
      'Comprehensive program supporting business students with leadership potential in the Asia-Pacific region.',
    requirements: 'Business or economics major, GPA 3.5+, international experience preferred',
    benefits: 'Tuition coverage, regional internships, executive mentorship',
    fields: 'Business Administration, Economics, Finance, Management',
    country: 'Japan',
    university: 'University of Tokyo',
    studyLevel: 'Master',
    scholarshipType: 'Full',
    fundingAmount: '40000 USD',
    startDate: new Date('2025-09-01').getTime(),
    endDate: new Date('2025-12-20').getTime(),
    availableSlots: 15,
    languageRequirement: 'IELTS 7.0 or TOEFL 100',
    gpaRequirement: 3.5,
    scholarshipMedias: [],
  },
  {
    id: 24,
    providerId: 9,
    title: 'Climate Change Research Fellowship',
    slug: 'climate-change-research-fellowship',
    shortDescription: 'Research opportunities in climate science.',
    description:
      'Fellowship for graduate students conducting research on climate change, adaptation, and mitigation strategies.',
    requirements: 'Graduate students in environmental or climate science, research proposal',
    benefits: 'Research funding, publication support, conference attendance',
    fields: 'Climate Science, Environmental Policy, Atmospheric Science',
    country: 'Switzerland',
    university: 'ETH Zurich',
    studyLevel: 'PhD',
    scholarshipType: 'Full',
    fundingAmount: '45000 USD',
    startDate: new Date('2025-10-01').getTime(),
    endDate: new Date('2026-01-31').getTime(),
    availableSlots: 8,
    languageRequirement: 'IELTS 7.5 or TOEFL 110',
    gpaRequirement: 3.6,
    scholarshipMedias: [],
  },
  {
    id: 25,
    providerId: 10,
    title: 'Digital Arts & Media Scholarship',
    slug: 'digital-arts-media-scholarship',
    shortDescription: 'Supporting creative digital media students.',
    description:
      'Scholarship for students pursuing digital arts, animation, game design, and interactive media.',
    requirements: 'Portfolio required, GPA 3.0+, passion for digital arts',
    benefits: 'Studio access, software licenses, industry connections',
    fields: 'Digital Arts, Animation, Game Design, Interactive Media',
    country: 'South Korea',
    university: 'Seoul National University',
    studyLevel: 'Bachelor',
    scholarshipType: 'Partial',
    fundingAmount: '15000 USD',
    startDate: new Date('2025-09-01').getTime(),
    endDate: new Date('2025-11-15').getTime(),
    availableSlots: 25,
    languageRequirement: 'IELTS 6.0 or TOEFL 80',
    gpaRequirement: 3.0,
    scholarshipMedias: [],
  },
  {
    id: 26,
    providerId: 11,
    title: 'Global Health Initiative Scholarship',
    slug: 'global-health-initiative',
    shortDescription: 'Advancing global health education.',
    description:
      'Supporting students dedicated to improving health outcomes in underserved communities worldwide.',
    requirements: 'Health sciences or public health major, volunteer experience, GPA 3.3+',
    benefits: 'Tuition support, field experience, global health network',
    fields: 'Public Health, Health Sciences, Global Health, Epidemiology',
    country: 'Netherlands',
    university: 'University of Amsterdam',
    studyLevel: 'Master',
    scholarshipType: 'Full',
    fundingAmount: '30000 USD',
    startDate: new Date('2025-08-15').getTime(),
    endDate: new Date('2025-11-30').getTime(),
    availableSlots: 12,
    languageRequirement: 'IELTS 6.5 or TOEFL 90',
    gpaRequirement: 3.3,
    scholarshipMedias: [],
  },
  {
    id: 27,
    providerId: 12,
    title: 'Renewable Energy Research Grant',
    slug: 'renewable-energy-research-grant',
    shortDescription: 'Funding for renewable energy research projects.',
    description:
      'Grants for research projects focusing on solar, wind, hydroelectric, and other renewable energy sources.',
    requirements: 'Engineering or physics background, research proposal, GPA 3.4+',
    benefits: 'Research funding, lab equipment, publication opportunities',
    fields: 'Renewable Energy, Energy Engineering, Physics',
    country: 'Sweden',
    university: 'KTH Royal Institute of Technology',
    studyLevel: 'PhD',
    scholarshipType: 'Full',
    fundingAmount: '50000 USD',
    startDate: new Date('2025-09-01').getTime(),
    endDate: new Date('2026-02-28').getTime(),
    availableSlots: 6,
    languageRequirement: 'IELTS 7.0 or TOEFL 100',
    gpaRequirement: 3.4,
    scholarshipMedias: [],
  },
  {
    id: 28,
    providerId: 13,
    title: 'Humanitarian Studies Fellowship',
    slug: 'humanitarian-studies-fellowship',
    shortDescription: 'Fellowship for humanitarian work studies.',
    description:
      'Supporting students committed to humanitarian work, disaster relief, and international aid.',
    requirements: 'Social sciences or international relations, field experience, GPA 3.2+',
    benefits: 'Field placement, networking, mentorship',
    fields: 'International Relations, Social Work, Humanitarian Studies',
    country: 'Belgium',
    university: 'KU Leuven',
    studyLevel: 'Master',
    scholarshipType: 'Partial',
    fundingAmount: '18000 USD',
    startDate: new Date('2025-09-15').getTime(),
    endDate: new Date('2025-12-10').getTime(),
    availableSlots: 14,
    languageRequirement: 'IELTS 6.5 or TOEFL 90',
    gpaRequirement: 3.2,
    scholarshipMedias: [],
  },
  {
    id: 29,
    providerId: 14,
    title: 'Data Science Excellence Scholarship',
    slug: 'data-science-excellence',
    shortDescription: 'Scholarship for data science and analytics students.',
    description:
      'Awarded to students with exceptional skills in data analysis, machine learning, and statistical modeling.',
    requirements: 'Data science or statistics major, coding portfolio, GPA 3.5+',
    benefits: 'Tuition coverage, industry internships, data science tools access',
    fields: 'Data Science, Statistics, Machine Learning, Analytics',
    country: 'Canada',
    university: 'University of Toronto',
    studyLevel: 'Master',
    scholarshipType: 'Full',
    fundingAmount: '28000 USD',
    startDate: new Date('2025-09-01').getTime(),
    endDate: new Date('2025-11-30').getTime(),
    availableSlots: 18,
    languageRequirement: 'IELTS 7.0 or TOEFL 100',
    gpaRequirement: 3.5,
    scholarshipMedias: [],
  },
  {
    id: 30,
    providerId: 15,
    title: 'Marine Biology Research Scholarship',
    slug: 'marine-biology-research',
    shortDescription: 'Supporting marine biology research and conservation.',
    description:
      'Scholarship for students researching marine ecosystems, conservation, and aquatic biodiversity.',
    requirements: 'Biology or marine science major, research interest, GPA 3.3+',
    benefits: 'Research vessel access, field research funding, publication support',
    fields: 'Marine Biology, Oceanography, Conservation Biology',
    country: 'Australia',
    university: 'University of Queensland',
    studyLevel: 'PhD',
    scholarshipType: 'Full',
    fundingAmount: '42000 USD',
    startDate: new Date('2025-10-01').getTime(),
    endDate: new Date('2026-01-15').getTime(),
    availableSlots: 7,
    languageRequirement: 'IELTS 7.0 or TOEFL 100',
    gpaRequirement: 3.3,
    scholarshipMedias: [],
  },
  {
    id: 31,
    providerId: 16,
    title: 'International Business Scholarship',
    slug: 'international-business-scholarship',
    shortDescription: 'Supporting global business education.',
    description:
      'Scholarship for students pursuing international business, trade, and global commerce studies.',
    requirements: 'Business major, international experience, GPA 3.4+',
    benefits: 'Study abroad opportunities, business network, mentorship',
    fields: 'International Business, Global Trade, Business Administration',
    country: 'France',
    university: 'INSEAD',
    studyLevel: 'Master',
    scholarshipType: 'Full',
    fundingAmount: '55000 USD',
    startDate: new Date('2025-08-01').getTime(),
    endDate: new Date('2025-10-31').getTime(),
    availableSlots: 10,
    languageRequirement: 'IELTS 7.5 or TOEFL 110',
    gpaRequirement: 3.4,
    scholarshipMedias: [],
  },
  {
    id: 32,
    providerId: 17,
    title: 'Urban Planning & Architecture Award',
    slug: 'urban-planning-architecture',
    shortDescription: 'Scholarship for future urban planners and architects.',
    description:
      'Supporting students in urban planning, architecture, and sustainable city development.',
    requirements: 'Architecture or urban planning major, portfolio, GPA 3.2+',
    benefits: 'Design studio access, internship opportunities, professional mentorship',
    fields: 'Architecture, Urban Planning, Landscape Architecture',
    country: 'Denmark',
    university: 'University of Copenhagen',
    studyLevel: 'Master',
    scholarshipType: 'Partial',
    fundingAmount: '22000 USD',
    startDate: new Date('2025-09-15').getTime(),
    endDate: new Date('2025-12-05').getTime(),
    availableSlots: 16,
    languageRequirement: 'IELTS 6.5 or TOEFL 90',
    gpaRequirement: 3.2,
    scholarshipMedias: [],
  },
  {
    id: 33,
    providerId: 18,
    title: 'Cybersecurity Excellence Scholarship',
    slug: 'cybersecurity-excellence',
    shortDescription: 'Supporting the next generation of cybersecurity experts.',
    description:
      'Scholarship for students specializing in cybersecurity, information security, and digital forensics.',
    requirements: 'Computer science or cybersecurity major, certifications preferred, GPA 3.4+',
    benefits: 'Certification support, industry connections, security tools access',
    fields: 'Cybersecurity, Information Security, Digital Forensics',
    country: 'Israel',
    university: 'Technion - Israel Institute of Technology',
    studyLevel: 'Master',
    scholarshipType: 'Full',
    fundingAmount: '32000 USD',
    startDate: new Date('2025-09-01').getTime(),
    endDate: new Date('2025-11-20').getTime(),
    availableSlots: 12,
    languageRequirement: 'IELTS 7.0 or TOEFL 100',
    gpaRequirement: 3.4,
    scholarshipMedias: [],
  },
  {
    id: 34,
    providerId: 19,
    title: 'Agricultural Innovation Grant',
    slug: 'agricultural-innovation-grant',
    shortDescription: 'Supporting innovation in agriculture and food security.',
    description:
      'Grants for students researching agricultural technology, sustainable farming, and food security solutions.',
    requirements: 'Agriculture or related field, research proposal, GPA 3.3+',
    benefits: 'Research funding, field access, agricultural network',
    fields: 'Agricultural Science, Agronomy, Food Security',
    country: 'New Zealand',
    university: 'University of Auckland',
    studyLevel: 'PhD',
    scholarshipType: 'Full',
    fundingAmount: '38000 USD',
    startDate: new Date('2025-10-15').getTime(),
    endDate: new Date('2026-01-31').getTime(),
    availableSlots: 9,
    languageRequirement: 'IELTS 6.5 or TOEFL 90',
    gpaRequirement: 3.3,
    scholarshipMedias: [],
  },
  {
    id: 35,
    providerId: 20,
    title: 'Linguistics & Language Studies Scholarship',
    slug: 'linguistics-language-studies',
    shortDescription: 'Supporting linguistic research and language preservation.',
    description:
      'Scholarship for students studying linguistics, language preservation, and multilingual communication.',
    requirements: 'Linguistics or language studies major, research interest, GPA 3.2+',
    benefits: 'Research support, language resources, academic network',
    fields: 'Linguistics, Applied Linguistics, Language Studies',
    country: 'United Kingdom',
    university: 'University of Oxford',
    studyLevel: 'PhD',
    scholarshipType: 'Full',
    fundingAmount: '48000 USD',
    startDate: new Date('2025-09-01').getTime(),
    endDate: new Date('2026-02-15').getTime(),
    availableSlots: 5,
    languageRequirement: 'IELTS 8.0 or TOEFL 115',
    gpaRequirement: 3.6,
    scholarshipMedias: [],
  },
];
