version: "3.9"

services:
  nginx:
    image:  nginx:1.27.2
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - m-network
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.14
    environment:
      - BASE_URL=/swagger-ui
      - URLS
      - OAUTH_CLIENT_ID=swagger-ui
      - OAUTH_USE_PKCE=true
    networks:
      - m-network
  identity:
    image: quay.io/keycloak/keycloak:26.0.2
    command: 'start-dev --import-realm'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: minh01672527656
      KC_HTTP_PORT: 80
      KC_PROXY: edge
      KC_HOSTNAME: api.edumatch.space
      KC_HTTP_RELATIVE_PATH: /identity
    volumes:
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./identity/themes/yas/theme:/opt/keycloak/themes
    networks:
      - m-network
  postgres:
    image: debezium/postgres:16-alpine
    build: ./docker/postgres
    hostname: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./docker/postgres/postgresql.conf.sample:/usr/share/postgresql/postgresql.conf.sample
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - postgres:/var/lib/postgresql/data
    command: postgres -c 'max_connections=500' -c 'timezone=UTC'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - m-network
  redis:
    image: redis:7.4.1-alpine
    restart: always
    environment:
      - SPRING_DATA_REDIS_HOST
      - SPRING_DATA_REDIS_PORT
    volumes:
      - redis:/data
    networks:
      - m-network
  registry-server:
    image: registry.edumatch.space/edumatch/registry:1.0.0
    volumes:
      - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
      - ./deployment/app-config:/app-config
    networks:
      - m-network
  customer:
    image: registry.edumatch.space/edumatch/customer:1.1.0
    volumes:
      - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
      - ./deployment/app-config:/app-config
    networks:
      - m-network
  profile:
    image: registry.edumatch.space/edumatch/profile:1.1.0
    volumes:
      - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
      - ./deployment/app-config:/app-config
    networks:
      - m-network
  media:
    image: registry.edumatch.space/edumatch/media:1.1.0
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_BUCKET_NAME
    volumes:
      - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
      - ./deployment/app-config:/app-config
    networks:
      - m-network
  notification:
    image: registry.edumatch.space/edumatch/notification:1.1.0
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_BUCKET_NAME
    volumes:
      - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
      - ./deployment/app-config:/app-config
    networks:
      - m-network
  subscription:
    image: registry.edumatch.space/edumatch/subscription:1.0.0
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_BUCKET_NAME
    volumes:
      - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
      - ./deployment/app-config:/app-config
    networks:
      - m-network
  scholarship:
    image: registry.edumatch.space/edumatch/scholarship:1.1.0
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_BUCKET_NAME
    volumes:
      - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
      - ./deployment/app-config:/app-config
    networks:
      - m-network
  search:
    image: registry.edumatch.space/edumatch/search:1.1.0
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_BUCKET_NAME
    volumes:
      - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
      - ./deployment/app-config:/app-config
    networks:
      - m-network
    depends_on:
      - elasticsearch
  report:
    image: registry.edumatch.space/edumatch/report:1.1.0
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_BUCKET_NAME
    volumes:
      - ./docker/libs/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
      - ./deployment/app-config:/app-config
    networks:
      - m-network
  ai-match:
    image: registry.edumatch.space/edumatch/ai-match:1.0.0
    env_file:
      - ./ai-match/.env
    networks:
      - m-network
  backoffice-nextjs:
    image: registry.edumatch.space/edumatch/backoffice-nextjs:1.0.0
    networks:
      - m-network
  edufront-nextjs:
    image: registry.edumatch.space/edumatch/edufront-nextjs:1.0.0
    networks:
      - m-network
  payment:
    image: registry.edumatch.space/edumatch/payment:1.1.0
    networks:
      - m-network
  zookeeper:
    image: debezium/zookeeper:2.7.3.Final
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - m-network
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    hostname: ${KAFKA_SERVICE_HOST}
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_SERVICE_PORT}:${KAFKA_SERVICE_PORT}
      - 29092:29092
    environment:
      - KAFKA_BROKER_ID
      - KAFKA_ZOOKEEPER_CONNECT
      - KAFKA_ADVERTISED_LISTENERS
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      - KAFKA_INTER_BROKER_LISTENER_NAME
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
    networks:
      - m-network
  kafka-connect:
    image: debezium/connect:2.7.3.Final
    restart: always
    ports:
      - 8083:8083
      - 5005:5005
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=kafka_connect_configs
      - OFFSET_STORAGE_TOPIC=kafka_connect_offsets
    networks:
      - m-network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - 8089:8080
    depends_on:
      - kafka
      - kafka-connect
    networks:
      - m-network
  elasticsearch:
    image: elasticsearch:8.6.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - m-network

networks:
  m-network:
    driver: bridge
    name: m-network

volumes:
  postgres:
  pgadmin:
  redis:
  esdata: