version: "3.9"

services:
  backoffice:
    image: registry.edumatch.space/edumatch/edufront:1.0.0
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - m-network
  redis:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - m-network

networks:
  m-network:
    driver: bridge
    name: m-network

volumes:
  redis:
