CREATE TABLE IF NOT EXISTS scholarship.SCHOLARSHIP_VIEW (
    id BIGSERIAL PRIMARY KEY,
    scholarship_id BIGINT,
    user_id VARCHAR(100),
    full_name VARCHAR(255),
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION NUMERIC NOT NULL DEFAULT 0,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);