CREATE TABLE IF NOT EXISTS scholarship.CASE_STUDY (
    id BIGSERIAL PRIMARY KEY,
    scholarship_id BIGINT,
    user_id VARCHAR(100),
    title VARCHAR(512),
    content TEXT,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION NUMERIC NOT NULL DEFAULT 0,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scholarship.APPLICATION_MEDIA (
    case_study_id BIGINT,
    media_id BIGINT
);