CREATE TABLE IF NOT EXISTS scholarship.APPLICATION_ATTRIBUTE (
    id BIGSERIAL PRIMARY KEY,
    application_id BIGINT,
    key VARCHAR(255),
    value TEXT,
    note TEXT NULL,
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION NUMERIC NOT NULL DEFAULT 0,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
