CREATE TABLE IF NOT EXISTS scholarship.APPLICATION_SCHOLARSHIP (
    id BIGSERIAL PRIMARY KEY,
    application_scholarship_name VARCHAR(255) DEFAULT '',
    scholarship_id BIGINT,
    application_id BIGINT,
    status VARCHAR(100),
    reviewed_at TIMESTAMP NULL,
    note TEXT NULL,
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION NUMERIC NOT NULL DEFAULT 0,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scholarship.SCHOLARSHIP_FOLLOWER (
    scholarship_id BIGINT,
    user_id VARCHAR(100),
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION NUMERIC NOT NULL DEFAULT 0,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);