ALTER TABLE scholarship.application
    ADD COLUMN IF NOT EXISTS career_goal TEXT,
    ADD COLUMN IF NOT EXISTS research_interest TEXT,
    ADD COLUMN IF NOT EXISTS academic_awards TEXT,
    ADD COLUMN IF NOT EXISTS publication_count INT,
    ADD COLUMN IF NOT EXISTS sat_score INT,
    ADD COLUMN IF NOT EXISTS act_score INT,
    ADD COLUMN IF NOT EXISTS gre_score INT,
    ADD COLUMN IF NOT EXISTS gmat_score INT,
    ADD COLUMN IF NOT EXISTS toefl_score INT,
    ADD COLUMN IF NOT EXISTS ielts_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS work_experience_years INT,
    ADD COLUMN IF NOT EXISTS class_rank INT,
    ADD COLUMN IF NOT EXISTS class_size INT,
    ADD COLUMN IF NOT EXISTS class_rank_percentile DECIMAL (5,2),
    ADD COLUMN IF NOT EXISTS age INT,
    ADD COLUMN IF NOT EXISTS citizenship VARCHAR (100),
    ADD COLUMN IF NOT EXISTS is_athlete BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS athletic_achievements TEXT;
