version: "1.0.0"

services:
  nextjs:
    ports:
      - 3024:3024
    container_name: edu_front
    image: edu_front:latest
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
