import { IApplicantProfile } from '@/lib/schemas';

export const DEFAULT_PROFILE_FORM_VALUES: IApplicantProfile = {
  applicantProfile: {
    contactName: '',
    firstName: '',
    lastName: '',
    phoneNumber: '',
    religion: '',
    hometown: '',
    citizenshipStatus: '',
    ethnicity: '',
    race: '',
    militaryFamilyHistory: false,
    disabilities: '',
    medicalConditions: '',
    favoriteActivities: '',
    sportsParticipated: '',
    studentActivities: '',
    organizationsJoined: '',
    researchExperience: '',
    careerGoals: '',
    overallGpa: 0,
    educationLevel: '',
    satScore: undefined,
    actScore: undefined,
    greScore: undefined,
    gmatScore: undefined,
    toeflScore: undefined,
    ieltsScore: undefined,
    languages: '',
    academicAwards: '',
    publicationCount: undefined,
    researchInterest: '',
    extracurricularActivities: '',
    preferredScholarshipType: '',
    preferredCountry: '',
    preferredMajor: '',
    type: 'Current',
    certificates: [],
    educationHistories: [],
    applicantPreferences: [],
    skills: [],
    intentions: [],
  },
};

export const COUNTRY_CODES = [
  { value: '+1 (US/CA)', label: '+1 (US/CA)' },
  { value: '+44 (UK)', label: '+44 (UK)' },
  { value: '+61 (AU)', label: '+61 (AU)' },
  { value: '+81 (JP)', label: '+81 (JP)' },
  { value: '+82 (KR)', label: '+82 (KR)' },
  { value: '+84 (VN)', label: '+84 (VN)' },
  { value: '+86 (CN)', label: '+86 (CN)' },
  { value: '+49 (DE)', label: '+49 (DE)' },
  { value: '+33 (FR)', label: '+33 (FR)' },
  { value: '+34 (ES)', label: '+34 (ES)' },
  { value: '+39 (IT)', label: '+39 (IT)' },
  { value: '+55 (BR)', label: '+55 (BR)' },
  { value: '+65 (SG)', label: '+65 (SG)' },
  { value: '+60 (MY)', label: '+60 (MY)' },
  { value: '+62 (ID)', label: '+62 (ID)' },
  { value: '+852 (HK)', label: '+852 (HK)' },
  { value: '+853 (MO)', label: '+853 (MO)' },
  { value: '+886 (TW)', label: '+886 (TW)' },
  { value: '+971 (AE)', label: '+971 (AE)' },
  { value: '+966 (SA)', label: '+966 (SA)' },
];

export const PHONE_TYPES = [
  { value: 'Mobile', label: 'Mobile' },
  { value: 'Home', label: 'Home' },
  { value: 'Work', label: 'Work' },
  { value: 'Other', label: 'Other' },
];

export const INSTITUTION_TYPES = [
  { value: 'High School', label: 'High School' },
  { value: 'Community College', label: 'Community College' },
  { value: 'University', label: 'University' },
  { value: 'Technical School', label: 'Technical School' },
  { value: 'Vocational School', label: 'Vocational School' },
  { value: 'Online School', label: 'Online School' },
  { value: 'International School', label: 'International School' },
];

// Activities and Interests Options
export const FAVORITE_ACTIVITIES = [
  { value: 'Piano', label: 'Piano' },
  { value: 'Guitar', label: 'Guitar' },
  { value: 'Violin', label: 'Violin' },
  { value: 'Singing', label: 'Singing' },
  { value: 'Dancing', label: 'Dancing' },
  { value: 'Painting', label: 'Painting' },
  { value: 'Drawing', label: 'Drawing' },
  { value: 'Photography', label: 'Photography' },
  { value: 'Theater', label: 'Theater' },
  { value: 'Acting', label: 'Acting' },
  { value: 'Writing', label: 'Writing' },
  { value: 'Reading', label: 'Reading' },
  { value: 'Cooking', label: 'Cooking' },
  { value: 'Gardening', label: 'Gardening' },
  { value: 'Chess', label: 'Chess' },
  { value: 'Video Games', label: 'Video Games' },
  { value: 'Board Games', label: 'Board Games' },
  { value: 'Meditation', label: 'Meditation' },
  { value: 'Yoga', label: 'Yoga' },
  { value: 'Hiking', label: 'Hiking' },
  { value: 'Travel', label: 'Travel' },
  { value: 'Volunteering', label: 'Volunteering' },
  { value: 'Crafting', label: 'Crafting' },
  { value: 'Knitting', label: 'Knitting' },
  { value: 'Woodworking', label: 'Woodworking' },
];

export const SPORTS_PARTICIPATED = [
  { value: 'Soccer', label: 'Soccer' },
  { value: 'Basketball', label: 'Basketball' },
  { value: 'Tennis', label: 'Tennis' },
  { value: 'Swimming', label: 'Swimming' },
  { value: 'Volleyball', label: 'Volleyball' },
  { value: 'Badminton', label: 'Badminton' },
  { value: 'Table Tennis', label: 'Table Tennis' },
  { value: 'Football', label: 'Football' },
  { value: 'Baseball', label: 'Baseball' },
  { value: 'Softball', label: 'Softball' },
  { value: 'Track and Field', label: 'Track and Field' },
  { value: 'Cross Country', label: 'Cross Country' },
  { value: 'Gymnastics', label: 'Gymnastics' },
  { value: 'Martial Arts', label: 'Martial Arts' },
  { value: 'Karate', label: 'Karate' },
  { value: 'Taekwondo', label: 'Taekwondo' },
  { value: 'Boxing', label: 'Boxing' },
  { value: 'Wrestling', label: 'Wrestling' },
  { value: 'Golf', label: 'Golf' },
  { value: 'Bowling', label: 'Bowling' },
  { value: 'Cycling', label: 'Cycling' },
  { value: 'Running', label: 'Running' },
  { value: 'Weightlifting', label: 'Weightlifting' },
  { value: 'Rock Climbing', label: 'Rock Climbing' },
  { value: 'Surfing', label: 'Surfing' },
  { value: 'Skateboarding', label: 'Skateboarding' },
  { value: 'Ice Skating', label: 'Ice Skating' },
  { value: 'Hockey', label: 'Hockey' },
  { value: 'Lacrosse', label: 'Lacrosse' },
  { value: 'Rugby', label: 'Rugby' },
];

export const STUDENT_ACTIVITIES = [
  { value: 'Student Council', label: 'Student Council' },
  { value: 'Debate Club', label: 'Debate Club' },
  { value: 'Model UN', label: 'Model UN' },
  { value: 'National Honor Society', label: 'National Honor Society' },
  { value: 'Beta Club', label: 'Beta Club' },
  { value: 'Key Club', label: 'Key Club' },
  { value: 'Interact Club', label: 'Interact Club' },
  { value: 'Leo Club', label: 'Leo Club' },
  { value: 'Future Business Leaders', label: 'Future Business Leaders' },
  { value: 'DECA', label: 'DECA' },
  { value: 'FBLA', label: 'FBLA' },
  { value: 'HOSA', label: 'HOSA' },
  { value: 'SkillsUSA', label: 'SkillsUSA' },
  { value: 'Robotics Club', label: 'Robotics Club' },
  { value: 'Coding Club', label: 'Coding Club' },
  { value: 'Science Olympiad', label: 'Science Olympiad' },
  { value: 'Math Club', label: 'Math Club' },
  { value: 'Chess Club', label: 'Chess Club' },
  { value: 'Art Club', label: 'Art Club' },
  { value: 'Music Club', label: 'Music Club' },
  { value: 'Drama Club', label: 'Drama Club' },
  { value: 'Choir', label: 'Choir' },
  { value: 'Band', label: 'Band' },
  { value: 'Orchestra', label: 'Orchestra' },
  { value: 'Yearbook Committee', label: 'Yearbook Committee' },
  { value: 'Newspaper Staff', label: 'Newspaper Staff' },
  { value: 'Literary Magazine', label: 'Literary Magazine' },
  { value: 'Peer Tutoring', label: 'Peer Tutoring' },
  { value: 'Mentoring Program', label: 'Mentoring Program' },
  { value: 'Environmental Club', label: 'Environmental Club' },
  { value: 'Gay-Straight Alliance', label: 'Gay-Straight Alliance' },
  { value: 'Cultural Club', label: 'Cultural Club' },
  { value: 'Language Club', label: 'Language Club' },
  { value: 'Book Club', label: 'Book Club' },
  { value: 'Photography Club', label: 'Photography Club' },
];

export const ORGANIZATIONS_JOINED = [
  { value: 'Red Cross', label: 'Red Cross' },
  { value: 'United Way', label: 'United Way' },
  { value: 'Habitat for Humanity', label: 'Habitat for Humanity' },
  { value: 'Salvation Army', label: 'Salvation Army' },
  { value: 'Boys and Girls Club', label: 'Boys and Girls Club' },
  { value: 'YMCA', label: 'YMCA' },
  { value: 'YWCA', label: 'YWCA' },
  { value: 'Scouts', label: 'Scouts' },
  { value: 'Girl Scouts', label: 'Girl Scouts' },
  { value: '4-H Club', label: '4-H Club' },
  { value: 'Rotary Club', label: 'Rotary Club' },
  { value: 'Kiwanis Club', label: 'Kiwanis Club' },
  { value: 'Lions Club', label: 'Lions Club' },
  { value: 'Toastmasters', label: 'Toastmasters' },
  { value: 'Junior Achievement', label: 'Junior Achievement' },
  { value: 'Big Brothers Big Sisters', label: 'Big Brothers Big Sisters' },
  { value: 'Make-A-Wish Foundation', label: 'Make-A-Wish Foundation' },
  { value: "St. Jude Children's Hospital", label: "St. Jude Children's Hospital" },
  { value: 'Special Olympics', label: 'Special Olympics' },
  { value: 'American Cancer Society', label: 'American Cancer Society' },
  { value: 'American Heart Association', label: 'American Heart Association' },
  { value: 'March of Dimes', label: 'March of Dimes' },
  { value: 'UNICEF', label: 'UNICEF' },
  { value: 'World Vision', label: 'World Vision' },
  { value: 'Doctors Without Borders', label: 'Doctors Without Borders' },
  { value: 'Amnesty International', label: 'Amnesty International' },
  { value: 'Greenpeace', label: 'Greenpeace' },
  { value: 'Sierra Club', label: 'Sierra Club' },
  { value: 'Nature Conservancy', label: 'Nature Conservancy' },
  { value: 'Local Food Bank', label: 'Local Food Bank' },
  { value: 'Animal Shelter', label: 'Animal Shelter' },
  { value: 'Senior Center', label: 'Senior Center' },
  { value: 'Hospital Volunteer', label: 'Hospital Volunteer' },
  { value: 'Library Volunteer', label: 'Library Volunteer' },
  { value: 'Museum Volunteer', label: 'Museum Volunteer' },
  { value: 'Church Youth Group', label: 'Church Youth Group' },
  { value: 'Community Garden', label: 'Community Garden' },
  { value: 'Environmental Cleanup', label: 'Environmental Cleanup' },
  { value: 'Tutoring Program', label: 'Tutoring Program' },
];

export const RESEARCH_EXPERIENCE = [
  { value: 'AI/ML Research', label: 'AI/ML Research' },
  { value: 'Computer Science Lab', label: 'Computer Science Lab' },
  { value: 'Biology Research', label: 'Biology Research' },
  { value: 'Chemistry Lab', label: 'Chemistry Lab' },
  { value: 'Physics Research', label: 'Physics Research' },
  { value: 'Mathematics Research', label: 'Mathematics Research' },
  { value: 'Psychology Research', label: 'Psychology Research' },
  { value: 'Sociology Research', label: 'Sociology Research' },
  { value: 'Economics Research', label: 'Economics Research' },
  { value: 'Political Science Research', label: 'Political Science Research' },
  { value: 'History Research', label: 'History Research' },
  { value: 'Literature Research', label: 'Literature Research' },
  { value: 'Linguistics Research', label: 'Linguistics Research' },
  { value: 'Anthropology Research', label: 'Anthropology Research' },
  { value: 'Environmental Science Research', label: 'Environmental Science Research' },
  { value: 'Geology Research', label: 'Geology Research' },
  { value: 'Astronomy Research', label: 'Astronomy Research' },
  { value: 'Engineering Research', label: 'Engineering Research' },
  { value: 'Biomedical Research', label: 'Biomedical Research' },
  { value: 'Neuroscience Research', label: 'Neuroscience Research' },
  { value: 'Genetics Research', label: 'Genetics Research' },
  { value: 'Climate Research', label: 'Climate Research' },
  { value: 'Marine Biology Research', label: 'Marine Biology Research' },
  { value: 'Botany Research', label: 'Botany Research' },
  { value: 'Zoology Research', label: 'Zoology Research' },
  { value: 'Ecology Research', label: 'Ecology Research' },
  { value: 'Microbiology Research', label: 'Microbiology Research' },
  { value: 'Biochemistry Research', label: 'Biochemistry Research' },
  { value: 'Molecular Biology Research', label: 'Molecular Biology Research' },
  { value: 'Cell Biology Research', label: 'Cell Biology Research' },
  { value: 'Immunology Research', label: 'Immunology Research' },
  { value: 'Pharmacology Research', label: 'Pharmacology Research' },
  { value: 'Toxicology Research', label: 'Toxicology Research' },
  { value: 'Public Health Research', label: 'Public Health Research' },
  { value: 'Epidemiology Research', label: 'Epidemiology Research' },
  { value: 'Clinical Research', label: 'Clinical Research' },
  { value: 'Educational Research', label: 'Educational Research' },
  { value: 'Business Research', label: 'Business Research' },
  { value: 'Marketing Research', label: 'Marketing Research' },
  { value: 'Social Work Research', label: 'Social Work Research' },
];

export const CAREER_GOALS = [
  { value: 'Software Engineer', label: 'Software Engineer' },
  { value: 'Data Scientist', label: 'Data Scientist' },
  { value: 'Doctor', label: 'Doctor' },
  { value: 'Nurse', label: 'Nurse' },
  { value: 'Teacher', label: 'Teacher' },
  { value: 'Lawyer', label: 'Lawyer' },
  { value: 'Engineer', label: 'Engineer' },
  { value: 'Architect', label: 'Architect' },
  { value: 'Psychologist', label: 'Psychologist' },
  { value: 'Researcher', label: 'Researcher' },
  { value: 'Scientist', label: 'Scientist' },
  { value: 'Business Analyst', label: 'Business Analyst' },
  { value: 'Marketing Manager', label: 'Marketing Manager' },
  { value: 'Financial Analyst', label: 'Financial Analyst' },
  { value: 'Investment Banker', label: 'Investment Banker' },
  { value: 'Consultant', label: 'Consultant' },
  { value: 'Entrepreneur', label: 'Entrepreneur' },
  { value: 'CEO', label: 'CEO' },
  { value: 'Product Manager', label: 'Product Manager' },
  { value: 'Project Manager', label: 'Project Manager' },
  { value: 'UX/UI Designer', label: 'UX/UI Designer' },
  { value: 'Graphic Designer', label: 'Graphic Designer' },
  { value: 'Artist', label: 'Artist' },
  { value: 'Writer', label: 'Writer' },
  { value: 'Journalist', label: 'Journalist' },
  { value: 'Photographer', label: 'Photographer' },
  { value: 'Videographer', label: 'Videographer' },
  { value: 'Musician', label: 'Musician' },
  { value: 'Actor', label: 'Actor' },
  { value: 'Director', label: 'Director' },
  { value: 'Social Worker', label: 'Social Worker' },
  { value: 'Counselor', label: 'Counselor' },
  { value: 'Therapist', label: 'Therapist' },
  { value: 'Physical Therapist', label: 'Physical Therapist' },
  { value: 'Occupational Therapist', label: 'Occupational Therapist' },
  { value: 'Pharmacist', label: 'Pharmacist' },
  { value: 'Dentist', label: 'Dentist' },
  { value: 'Veterinarian', label: 'Veterinarian' },
  { value: 'Pilot', label: 'Pilot' },
  { value: 'Military Officer', label: 'Military Officer' },
  { value: 'Police Officer', label: 'Police Officer' },
  { value: 'Firefighter', label: 'Firefighter' },
  { value: 'Paramedic', label: 'Paramedic' },
  { value: 'Chef', label: 'Chef' },
  { value: 'Restaurant Owner', label: 'Restaurant Owner' },
  { value: 'Real Estate Agent', label: 'Real Estate Agent' },
  { value: 'Insurance Agent', label: 'Insurance Agent' },
  { value: 'Sales Representative', label: 'Sales Representative' },
  { value: 'Human Resources Manager', label: 'Human Resources Manager' },
  { value: 'Public Relations Specialist', label: 'Public Relations Specialist' },
  { value: 'Event Planner', label: 'Event Planner' },
  { value: 'Travel Agent', label: 'Travel Agent' },
  { value: 'Tour Guide', label: 'Tour Guide' },
  { value: 'Translator', label: 'Translator' },
  { value: 'Interpreter', label: 'Interpreter' },
  { value: 'Librarian', label: 'Librarian' },
  { value: 'Curator', label: 'Curator' },
  { value: 'Museum Director', label: 'Museum Director' },
  { value: 'Non-profit Director', label: 'Non-profit Director' },
  { value: 'Government Official', label: 'Government Official' },
  { value: 'Diplomat', label: 'Diplomat' },
  { value: 'International Relations Specialist', label: 'International Relations Specialist' },
  { value: 'Environmental Scientist', label: 'Environmental Scientist' },
  { value: 'Climate Change Analyst', label: 'Climate Change Analyst' },
  { value: 'Sustainability Manager', label: 'Sustainability Manager' },
  { value: 'Renewable Energy Engineer', label: 'Renewable Energy Engineer' },
  { value: 'Biomedical Engineer', label: 'Biomedical Engineer' },
  { value: 'Mechanical Engineer', label: 'Mechanical Engineer' },
  { value: 'Electrical Engineer', label: 'Electrical Engineer' },
  { value: 'Civil Engineer', label: 'Civil Engineer' },
  { value: 'Chemical Engineer', label: 'Chemical Engineer' },
  { value: 'Aerospace Engineer', label: 'Aerospace Engineer' },
  { value: 'Computer Engineer', label: 'Computer Engineer' },
  { value: 'Cybersecurity Specialist', label: 'Cybersecurity Specialist' },
  { value: 'Network Administrator', label: 'Network Administrator' },
  { value: 'Database Administrator', label: 'Database Administrator' },
  { value: 'Systems Analyst', label: 'Systems Analyst' },
  { value: 'IT Manager', label: 'IT Manager' },
  { value: 'Web Developer', label: 'Web Developer' },
  { value: 'Mobile App Developer', label: 'Mobile App Developer' },
  { value: 'Game Developer', label: 'Game Developer' },
  { value: 'DevOps Engineer', label: 'DevOps Engineer' },
  { value: 'Cloud Engineer', label: 'Cloud Engineer' },
  { value: 'Machine Learning Engineer', label: 'Machine Learning Engineer' },
  { value: 'AI Researcher', label: 'AI Researcher' },
  { value: 'Robotics Engineer', label: 'Robotics Engineer' },
  { value: 'Quantum Computing Researcher', label: 'Quantum Computing Researcher' },
  { value: 'Blockchain Developer', label: 'Blockchain Developer' },
  { value: 'Digital Marketing Specialist', label: 'Digital Marketing Specialist' },
  { value: 'Content Creator', label: 'Content Creator' },
  { value: 'Influencer', label: 'Influencer' },
  { value: 'Podcaster', label: 'Podcaster' },
  { value: 'Youtuber', label: 'Youtuber' },
  { value: 'Streamer', label: 'Streamer' },
  { value: 'E-sports Player', label: 'E-sports Player' },
  { value: 'Professional Athlete', label: 'Professional Athlete' },
  { value: 'Coach', label: 'Coach' },
  { value: 'Sports Commentator', label: 'Sports Commentator' },
  { value: 'Sports Journalist', label: 'Sports Journalist' },
  { value: 'Fitness Trainer', label: 'Fitness Trainer' },
  { value: 'Nutritionist', label: 'Nutritionist' },
  { value: 'Dietitian', label: 'Dietitian' },
  { value: 'Personal Trainer', label: 'Personal Trainer' },
  { value: 'Yoga Instructor', label: 'Yoga Instructor' },
  { value: 'Dance Instructor', label: 'Dance Instructor' },
  { value: 'Music Teacher', label: 'Music Teacher' },
  { value: 'Art Teacher', label: 'Art Teacher' },
  { value: 'Language Teacher', label: 'Language Teacher' },
  { value: 'Professor', label: 'Professor' },
  { value: 'Academic Researcher', label: 'Academic Researcher' },
  { value: 'College Administrator', label: 'College Administrator' },
  { value: 'School Principal', label: 'School Principal' },
  { value: 'School Counselor', label: 'School Counselor' },
  { value: 'Special Education Teacher', label: 'Special Education Teacher' },
  { value: 'Curriculum Developer', label: 'Curriculum Developer' },
  { value: 'Educational Technology Specialist', label: 'Educational Technology Specialist' },
  { value: 'Training and Development Specialist', label: 'Training and Development Specialist' },
  { value: 'Career Counselor', label: 'Career Counselor' },
  { value: 'College Admissions Counselor', label: 'College Admissions Counselor' },
  { value: 'Financial Aid Counselor', label: 'Financial Aid Counselor' },
  { value: 'Student Affairs Professional', label: 'Student Affairs Professional' },
  { value: 'Study Abroad Coordinator', label: 'Study Abroad Coordinator' },
  { value: 'International Student Advisor', label: 'International Student Advisor' },
  { value: 'Academic Advisor', label: 'Academic Advisor' },
  { value: 'Graduate Student', label: 'Graduate Student' },
  { value: 'PhD Student', label: 'PhD Student' },
  { value: 'Postdoctoral Researcher', label: 'Postdoctoral Researcher' },
  { value: 'Research Assistant', label: 'Research Assistant' },
  { value: 'Teaching Assistant', label: 'Teaching Assistant' },
  { value: 'Lab Technician', label: 'Lab Technician' },
  { value: 'Research Coordinator', label: 'Research Coordinator' },
  { value: 'Grant Writer', label: 'Grant Writer' },
  { value: 'Science Writer', label: 'Science Writer' },
  { value: 'Medical Writer', label: 'Medical Writer' },
  { value: 'Technical Writer', label: 'Technical Writer' },
  { value: 'Patent Attorney', label: 'Patent Attorney' },
  { value: 'Intellectual Property Lawyer', label: 'Intellectual Property Lawyer' },
  { value: 'Corporate Lawyer', label: 'Corporate Lawyer' },
  { value: 'Criminal Lawyer', label: 'Criminal Lawyer' },
  { value: 'Family Lawyer', label: 'Family Lawyer' },
  { value: 'Immigration Lawyer', label: 'Immigration Lawyer' },
  { value: 'Environmental Lawyer', label: 'Environmental Lawyer' },
  { value: 'Human Rights Lawyer', label: 'Human Rights Lawyer' },
  { value: 'Judge', label: 'Judge' },
  { value: 'Paralegal', label: 'Paralegal' },
  { value: 'Legal Assistant', label: 'Legal Assistant' },
  { value: 'Court Reporter', label: 'Court Reporter' },
  { value: 'Compliance Officer', label: 'Compliance Officer' },
  { value: 'Risk Manager', label: 'Risk Manager' },
  { value: 'Auditor', label: 'Auditor' },
  { value: 'Accountant', label: 'Accountant' },
  { value: 'Tax Advisor', label: 'Tax Advisor' },
  { value: 'Investment Advisor', label: 'Investment Advisor' },
  { value: 'Portfolio Manager', label: 'Portfolio Manager' },
  { value: 'Wealth Manager', label: 'Wealth Manager' },
  { value: 'Insurance Underwriter', label: 'Insurance Underwriter' },
  { value: 'Claims Adjuster', label: 'Claims Adjuster' },
  { value: 'Actuary', label: 'Actuary' },
  { value: 'Loan Officer', label: 'Loan Officer' },
  { value: 'Mortgage Broker', label: 'Mortgage Broker' },
  { value: 'Real Estate Appraiser', label: 'Real Estate Appraiser' },
  { value: 'Property Manager', label: 'Property Manager' },
  { value: 'Construction Manager', label: 'Construction Manager' },
  { value: 'Urban Planner', label: 'Urban Planner' },
  { value: 'Landscape Architect', label: 'Landscape Architect' },
  { value: 'Interior Designer', label: 'Interior Designer' },
  { value: 'Fashion Designer', label: 'Fashion Designer' },
  { value: 'Industrial Designer', label: 'Industrial Designer' },
  { value: 'Product Designer', label: 'Product Designer' },
  { value: 'Jewelry Designer', label: 'Jewelry Designer' },
  { value: 'Textile Designer', label: 'Textile Designer' },
  { value: 'Nail Technician', label: 'Nail Technician' },
  { value: 'Esthetician', label: 'Esthetician' },
  { value: 'Massage Therapist', label: 'Massage Therapist' },
  { value: 'Acupuncturist', label: 'Acupuncturist' },
  { value: 'Chiropractor', label: 'Chiropractor' },
  { value: 'Optometrist', label: 'Optometrist' },
  { value: 'Podiatrist', label: 'Podiatrist' },
  { value: 'Audiologist', label: 'Audiologist' },
  { value: 'Speech Therapist', label: 'Speech Therapist' },
  { value: 'Respiratory Therapist', label: 'Respiratory Therapist' },
  { value: 'Radiology Technician', label: 'Radiology Technician' },
  { value: 'Ultrasound Technician', label: 'Ultrasound Technician' },
  { value: 'Laboratory Technician', label: 'Laboratory Technician' },
  { value: 'Pharmacy Technician', label: 'Pharmacy Technician' },
  { value: 'Medical Assistant', label: 'Medical Assistant' },
  { value: 'Dental Hygienist', label: 'Dental Hygienist' },
  { value: 'Dental Assistant', label: 'Dental Assistant' },
  { value: 'Veterinary Technician', label: 'Veterinary Technician' },
  { value: 'Animal Trainer', label: 'Animal Trainer' },
  { value: 'Zookeeper', label: 'Zookeeper' },
  { value: 'Wildlife Biologist', label: 'Wildlife Biologist' },
  { value: 'Park Ranger', label: 'Park Ranger' },
  { value: 'Forester', label: 'Forester' },
  { value: 'Agricultural Scientist', label: 'Agricultural Scientist' },
  { value: 'Food Scientist', label: 'Food Scientist' },
  { value: 'Quality Assurance Specialist', label: 'Quality Assurance Specialist' },
  { value: 'Safety Inspector', label: 'Safety Inspector' },
  { value: 'Environmental Inspector', label: 'Environmental Inspector' },
  { value: 'Building Inspector', label: 'Building Inspector' },
  { value: 'Health Inspector', label: 'Health Inspector' },
  { value: 'Fire Inspector', label: 'Fire Inspector' },
  { value: 'Insurance Investigator', label: 'Insurance Investigator' },
  { value: 'Private Investigator', label: 'Private Investigator' },
  { value: 'Security Guard', label: 'Security Guard' },
  { value: 'Bodyguard', label: 'Bodyguard' },
  { value: 'Bounty Hunter', label: 'Bounty Hunter' },
  { value: 'Corrections Officer', label: 'Corrections Officer' },
  { value: 'Border Patrol Agent', label: 'Border Patrol Agent' },
  { value: 'Customs Officer', label: 'Customs Officer' },
  { value: 'Immigration Officer', label: 'Immigration Officer' },
  { value: 'TSA Agent', label: 'TSA Agent' },
  { value: 'Air Marshal', label: 'Air Marshal' },
  { value: 'Secret Service Agent', label: 'Secret Service Agent' },
  { value: 'FBI Agent', label: 'FBI Agent' },
  { value: 'DEA Agent', label: 'DEA Agent' },
  { value: 'CIA Agent', label: 'CIA Agent' },
  { value: 'NSA Agent', label: 'NSA Agent' },
  { value: 'Intelligence Analyst', label: 'Intelligence Analyst' },
  { value: 'Counterintelligence Specialist', label: 'Counterintelligence Specialist' },
  { value: 'Cybersecurity Analyst', label: 'Cybersecurity Analyst' },
  { value: 'Digital Forensics Specialist', label: 'Digital Forensics Specialist' },
  { value: 'Ethical Hacker', label: 'Ethical Hacker' },
  { value: 'Penetration Tester', label: 'Penetration Tester' },
  { value: 'Information Security Manager', label: 'Information Security Manager' },
  { value: 'Privacy Officer', label: 'Privacy Officer' },
  { value: 'Compliance Manager', label: 'Compliance Manager' },
  { value: 'Risk Analyst', label: 'Risk Analyst' },
  { value: 'Fraud Investigator', label: 'Fraud Investigator' },
  { value: 'Forensic Accountant', label: 'Forensic Accountant' },
  { value: 'Forensic Scientist', label: 'Forensic Scientist' },
  { value: 'Crime Scene Investigator', label: 'Crime Scene Investigator' },
  { value: 'Detective', label: 'Detective' },
  { value: 'Criminal Profiler', label: 'Criminal Profiler' },
  { value: 'Victim Advocate', label: 'Victim Advocate' },
  { value: 'Probation Officer', label: 'Probation Officer' },
  { value: 'Parole Officer', label: 'Parole Officer' },
  { value: 'Juvenile Justice Specialist', label: 'Juvenile Justice Specialist' },
  { value: 'Child Protective Services Worker', label: 'Child Protective Services Worker' },
  { value: 'Adult Protective Services Worker', label: 'Adult Protective Services Worker' },
  { value: 'Foster Care Coordinator', label: 'Foster Care Coordinator' },
  { value: 'Adoption Specialist', label: 'Adoption Specialist' },
  { value: 'Family Court Mediator', label: 'Family Court Mediator' },
  { value: 'Divorce Mediator', label: 'Divorce Mediator' },
  { value: 'Child Custody Evaluator', label: 'Child Custody Evaluator' },
  { value: 'Guardian ad Litem', label: 'Guardian ad Litem' },
  { value: 'Court Appointed Special Advocate', label: 'Court Appointed Special Advocate' },
  { value: 'Public Defender', label: 'Public Defender' },
  { value: 'Prosecutor', label: 'Prosecutor' },
  { value: 'District Attorney', label: 'District Attorney' },
  { value: 'Attorney General', label: 'Attorney General' },
  { value: 'Supreme Court Justice', label: 'Supreme Court Justice' },
  { value: 'Federal Judge', label: 'Federal Judge' },
  { value: 'State Judge', label: 'State Judge' },
  { value: 'Magistrate Judge', label: 'Magistrate Judge' },
  { value: 'Bankruptcy Judge', label: 'Bankruptcy Judge' },
  { value: 'Tax Court Judge', label: 'Tax Court Judge' },
  { value: 'Administrative Law Judge', label: 'Administrative Law Judge' },
  { value: 'Arbitrator', label: 'Arbitrator' },
  { value: 'Mediator', label: 'Mediator' },
  { value: 'Conciliator', label: 'Conciliator' },
  { value: 'Ombudsman', label: 'Ombudsman' },
  { value: 'Consumer Advocate', label: 'Consumer Advocate' },
  { value: 'Patient Advocate', label: 'Patient Advocate' },
  { value: 'Disability Rights Advocate', label: 'Disability Rights Advocate' },
  { value: 'Civil Rights Attorney', label: 'Civil Rights Attorney' },
  { value: 'Employment Lawyer', label: 'Employment Lawyer' },
  { value: "Workers' Compensation Attorney", label: "Workers' Compensation Attorney" },
  { value: 'Personal Injury Lawyer', label: 'Personal Injury Lawyer' },
  { value: 'Medical Malpractice Attorney', label: 'Medical Malpractice Attorney' },
  { value: 'Product Liability Lawyer', label: 'Product Liability Lawyer' },
  { value: 'Class Action Attorney', label: 'Class Action Attorney' },
  { value: 'Securities Lawyer', label: 'Securities Lawyer' },
  { value: 'Banking Lawyer', label: 'Banking Lawyer' },
  { value: 'Real Estate Attorney', label: 'Real Estate Attorney' },
  { value: 'Estate Planning Lawyer', label: 'Estate Planning Lawyer' },
  { value: 'Tax Attorney', label: 'Tax Attorney' },
  { value: 'Immigration Attorney', label: 'Immigration Attorney' },
  { value: 'Asylum Attorney', label: 'Asylum Attorney' },
  { value: 'Refugee Resettlement Specialist', label: 'Refugee Resettlement Specialist' },
  { value: 'International Development Worker', label: 'International Development Worker' },
  { value: 'Humanitarian Aid Worker', label: 'Humanitarian Aid Worker' },
  { value: 'Peace Corps Volunteer', label: 'Peace Corps Volunteer' },
  { value: 'Missionary', label: 'Missionary' },
  { value: 'Chaplain', label: 'Chaplain' },
  { value: 'Pastor', label: 'Pastor' },
  { value: 'Priest', label: 'Priest' },
  { value: 'Rabbi', label: 'Rabbi' },
  { value: 'Imam', label: 'Imam' },
  { value: 'Monk', label: 'Monk' },
  { value: 'Nun', label: 'Nun' },
  { value: 'Religious Education Director', label: 'Religious Education Director' },
  { value: 'Youth Minister', label: 'Youth Minister' },
  { value: 'Music Minister', label: 'Music Minister' },
  { value: 'Worship Leader', label: 'Worship Leader' },
  { value: 'Church Administrator', label: 'Church Administrator' },
  { value: 'Parish Secretary', label: 'Parish Secretary' },
  { value: 'Sacristan', label: 'Sacristan' },
  { value: 'Cantor', label: 'Cantor' },
  { value: 'Organist', label: 'Organist' },
  { value: 'Choir Director', label: 'Choir Director' },
  { value: 'Band Director', label: 'Band Director' },
  { value: 'Orchestra Conductor', label: 'Orchestra Conductor' },
  { value: 'Music Composer', label: 'Music Composer' },
  { value: 'Songwriter', label: 'Songwriter' },
  { value: 'Music Producer', label: 'Music Producer' },
  { value: 'Sound Engineer', label: 'Sound Engineer' },
  { value: 'Recording Engineer', label: 'Recording Engineer' },
  { value: 'Audio Engineer', label: 'Audio Engineer' },
  { value: 'Live Sound Engineer', label: 'Live Sound Engineer' },
  { value: 'Broadcast Engineer', label: 'Broadcast Engineer' },
  { value: 'Radio DJ', label: 'Radio DJ' },
  { value: 'Television Host', label: 'Television Host' },
  { value: 'News Anchor', label: 'News Anchor' },
  { value: 'Weather Reporter', label: 'Weather Reporter' },
  { value: 'Sports Reporter', label: 'Sports Reporter' },
  { value: 'Investigative Reporter', label: 'Investigative Reporter' },
  { value: 'Photojournalist', label: 'Photojournalist' },
  { value: 'War Correspondent', label: 'War Correspondent' },
  { value: 'Foreign Correspondent', label: 'Foreign Correspondent' },
  { value: 'Political Reporter', label: 'Political Reporter' },
  { value: 'Business Reporter', label: 'Business Reporter' },
  { value: 'Technology Reporter', label: 'Technology Reporter' },
  { value: 'Science Reporter', label: 'Science Reporter' },
  { value: 'Health Reporter', label: 'Health Reporter' },
  { value: 'Education Reporter', label: 'Education Reporter' },
  { value: 'Crime Reporter', label: 'Crime Reporter' },
  { value: 'Entertainment Reporter', label: 'Entertainment Reporter' },
  { value: 'Celebrity Reporter', label: 'Celebrity Reporter' },
  { value: 'Gossip Columnist', label: 'Gossip Columnist' },
  { value: 'Fashion Reporter', label: 'Fashion Reporter' },
  { value: 'Lifestyle Reporter', label: 'Lifestyle Reporter' },
  { value: 'Travel Reporter', label: 'Travel Reporter' },
  { value: 'Food Critic', label: 'Food Critic' },
  { value: 'Restaurant Critic', label: 'Restaurant Critic' },
  { value: 'Movie Critic', label: 'Movie Critic' },
  { value: 'Book Critic', label: 'Book Critic' },
  { value: 'Music Critic', label: 'Music Critic' },
  { value: 'Art Critic', label: 'Art Critic' },
  { value: 'Theater Critic', label: 'Theater Critic' },
  { value: 'Dance Critic', label: 'Dance Critic' },
  { value: 'Sports Critic', label: 'Sports Critic' },
  { value: 'Editorial Writer', label: 'Editorial Writer' },
  { value: 'Opinion Columnist', label: 'Opinion Columnist' },
  { value: 'Political Columnist', label: 'Political Columnist' },
  { value: 'Humor Columnist', label: 'Humor Columnist' },
  { value: 'Advice Columnist', label: 'Advice Columnist' },
  { value: 'Health Columnist', label: 'Health Columnist' },
  { value: 'Finance Columnist', label: 'Finance Columnist' },
  { value: 'Technology Columnist', label: 'Technology Columnist' },
  { value: 'Science Columnist', label: 'Science Columnist' },
  { value: 'Environment Columnist', label: 'Environment Columnist' },
  { value: 'Social Issues Columnist', label: 'Social Issues Columnist' },
  { value: 'Cultural Columnist', label: 'Cultural Columnist' },
  { value: 'Religious Columnist', label: 'Religious Columnist' },
  { value: 'Spiritual Columnist', label: 'Spiritual Columnist' },
  { value: 'Inspirational Speaker', label: 'Inspirational Speaker' },
  { value: 'Motivational Speaker', label: 'Motivational Speaker' },
  { value: 'Life Coach', label: 'Life Coach' },
  { value: 'Career Coach', label: 'Career Coach' },
  { value: 'Business Coach', label: 'Business Coach' },
  { value: 'Executive Coach', label: 'Executive Coach' },
  { value: 'Leadership Coach', label: 'Leadership Coach' },
  { value: 'Team Building Facilitator', label: 'Team Building Facilitator' },
  { value: 'Conflict Resolution Specialist', label: 'Conflict Resolution Specialist' },
  { value: 'Negotiation Specialist', label: 'Negotiation Specialist' },
  { value: 'Communication Specialist', label: 'Communication Specialist' },
  { value: 'Public Speaking Coach', label: 'Public Speaking Coach' },
  { value: 'Presentation Skills Trainer', label: 'Presentation Skills Trainer' },
  { value: 'Media Training Specialist', label: 'Media Training Specialist' },
  { value: 'Crisis Communication Specialist', label: 'Crisis Communication Specialist' },
  { value: 'Reputation Management Specialist', label: 'Reputation Management Specialist' },
  { value: 'Brand Management Specialist', label: 'Brand Management Specialist' },
  { value: 'Marketing Communications Manager', label: 'Marketing Communications Manager' },
  { value: 'Content Marketing Manager', label: 'Content Marketing Manager' },
  { value: 'Social Media Manager', label: 'Social Media Manager' },
  { value: 'Community Manager', label: 'Community Manager' },
  { value: 'Influencer Marketing Manager', label: 'Influencer Marketing Manager' },
  { value: 'Affiliate Marketing Manager', label: 'Affiliate Marketing Manager' },
  { value: 'Email Marketing Manager', label: 'Email Marketing Manager' },
  { value: 'Search Engine Marketing Specialist', label: 'Search Engine Marketing Specialist' },
  { value: 'Pay-Per-Click Specialist', label: 'Pay-Per-Click Specialist' },
  {
    value: 'Search Engine Optimization Specialist',
    label: 'Search Engine Optimization Specialist',
  },
  {
    value: 'Conversion Rate Optimization Specialist',
    label: 'Conversion Rate Optimization Specialist',
  },
  { value: 'A/B Testing Specialist', label: 'A/B Testing Specialist' },
  { value: 'User Experience Researcher', label: 'User Experience Researcher' },
  { value: 'User Interface Designer', label: 'User Interface Designer' },
  { value: 'Interaction Designer', label: 'Interaction Designer' },
  { value: 'Information Architect', label: 'Information Architect' },
  { value: 'Usability Specialist', label: 'Usability Specialist' },
  { value: 'Accessibility Specialist', label: 'Accessibility Specialist' },
  { value: 'Frontend Developer', label: 'Frontend Developer' },
  { value: 'Backend Developer', label: 'Backend Developer' },
  { value: 'Full Stack Developer', label: 'Full Stack Developer' },
  { value: 'Mobile Developer', label: 'Mobile Developer' },
  { value: 'iOS Developer', label: 'iOS Developer' },
  { value: 'Android Developer', label: 'Android Developer' },
  { value: 'React Native Developer', label: 'React Native Developer' },
  { value: 'Flutter Developer', label: 'Flutter Developer' },
  { value: 'Xamarin Developer', label: 'Xamarin Developer' },
  { value: 'Unity Developer', label: 'Unity Developer' },
  { value: 'Unreal Engine Developer', label: 'Unreal Engine Developer' },
  { value: 'Game Designer', label: 'Game Designer' },
  { value: 'Level Designer', label: 'Level Designer' },
  { value: 'Environment Artist', label: 'Environment Artist' },
  { value: '3D Modeler', label: '3D Modeler' },
  { value: 'Texture Artist', label: 'Texture Artist' },
  { value: 'Animation Artist', label: 'Animation Artist' },
  { value: 'Rigging Artist', label: 'Rigging Artist' },
  { value: 'Lighting Artist', label: 'Lighting Artist' },
  { value: 'VFX Artist', label: 'VFX Artist' },
  { value: 'Compositor', label: 'Compositor' },
  { value: 'Motion Graphics Artist', label: 'Motion Graphics Artist' },
  { value: 'Video Editor', label: 'Video Editor' },
  { value: 'Film Editor', label: 'Film Editor' },
  { value: 'Foley Artist', label: 'Foley Artist' },
  { value: 'Music Supervisor', label: 'Music Supervisor' },
  { value: 'Film Producer', label: 'Film Producer' },
  { value: 'Television Producer', label: 'Television Producer' },
  { value: 'Documentary Producer', label: 'Documentary Producer' },
  { value: 'Commercial Producer', label: 'Commercial Producer' },
  { value: 'Music Video Producer', label: 'Music Video Producer' },
  { value: 'Podcast Producer', label: 'Podcast Producer' },
  { value: 'Radio Producer', label: 'Radio Producer' },
  { value: 'Audio Producer', label: 'Audio Producer' },
  { value: 'Content Producer', label: 'Content Producer' },
  { value: 'Creative Producer', label: 'Creative Producer' },
  { value: 'Line Producer', label: 'Line Producer' },
  { value: 'Associate Producer', label: 'Associate Producer' },
  { value: 'Executive Producer', label: 'Executive Producer' },
  { value: 'Co-Producer', label: 'Co-Producer' },
  { value: 'Supervising Producer', label: 'Supervising Producer' },
  { value: 'Development Producer', label: 'Development Producer' },
  { value: 'Post-Production Producer', label: 'Post-Production Producer' },
  { value: 'Location Manager', label: 'Location Manager' },
  { value: 'Production Manager', label: 'Production Manager' },
  { value: 'Unit Production Manager', label: 'Unit Production Manager' },
  { value: 'Assistant Director', label: 'Assistant Director' },
  { value: 'Second Assistant Director', label: 'Second Assistant Director' },
  { value: 'Third Assistant Director', label: 'Third Assistant Director' },
  { value: 'Script Supervisor', label: 'Script Supervisor' },
  { value: 'Continuity Supervisor', label: 'Continuity Supervisor' },
  { value: 'Production Coordinator', label: 'Production Coordinator' },
  { value: 'Production Assistant', label: 'Production Assistant' },
  { value: 'Set Decorator', label: 'Set Decorator' },
  { value: 'Prop Master', label: 'Prop Master' },
  { value: 'Costume Designer', label: 'Costume Designer' },
  { value: 'Wardrobe Supervisor', label: 'Wardrobe Supervisor' },
  { value: 'Hair Stylist', label: 'Hair Stylist' },
  { value: 'Makeup Artist', label: 'Makeup Artist' },
  { value: 'Special Effects Makeup Artist', label: 'Special Effects Makeup Artist' },
  { value: 'Stunt Coordinator', label: 'Stunt Coordinator' },
  { value: 'Stunt Performer', label: 'Stunt Performer' },
  { value: 'Dialect Coach', label: 'Dialect Coach' },
  { value: 'Acting Coach', label: 'Acting Coach' },
  { value: 'Voice Coach', label: 'Voice Coach' },
  { value: 'Movement Coach', label: 'Movement Coach' },
  { value: 'Fight Choreographer', label: 'Fight Choreographer' },
  { value: 'Dance Choreographer', label: 'Dance Choreographer' },
  { value: 'Casting Director', label: 'Casting Director' },
  { value: 'Casting Assistant', label: 'Casting Assistant' },
  { value: 'Talent Agent', label: 'Talent Agent' },
  { value: 'Talent Manager', label: 'Talent Manager' },
  { value: 'Entertainment Lawyer', label: 'Entertainment Lawyer' },
  { value: 'Entertainment Accountant', label: 'Entertainment Accountant' },
  { value: 'Entertainment Publicist', label: 'Entertainment Publicist' },
  { value: 'Celebrity Manager', label: 'Celebrity Manager' },
  { value: 'Artist Manager', label: 'Artist Manager' },
  { value: 'Band Manager', label: 'Band Manager' },
  { value: 'Tour Manager', label: 'Tour Manager' },
  { value: 'Booking Agent', label: 'Booking Agent' },
  { value: 'Concert Promoter', label: 'Concert Promoter' },
  { value: 'Festival Director', label: 'Festival Director' },
  { value: 'Venue Manager', label: 'Venue Manager' },
  { value: 'Stage Manager', label: 'Stage Manager' },
  { value: 'Technical Director', label: 'Technical Director' },
  { value: 'Lighting Designer', label: 'Lighting Designer' },
  { value: 'Sound Designer', label: 'Sound Designer' },
  { value: 'Scenic Designer', label: 'Scenic Designer' },
  { value: 'Hair and Makeup Designer', label: 'Hair and Makeup Designer' },
  { value: 'Properties Designer', label: 'Properties Designer' },
  { value: 'Projection Designer', label: 'Projection Designer' },
  { value: 'Video Designer', label: 'Video Designer' },
  { value: 'Automation Designer', label: 'Automation Designer' },
  { value: 'Rigging Designer', label: 'Rigging Designer' },
  { value: 'Pyrotechnics Designer', label: 'Pyrotechnics Designer' },
  { value: 'Special Effects Designer', label: 'Special Effects Designer' },
  { value: 'Props Master', label: 'Props Master' },
  { value: 'Wardrobe Master', label: 'Wardrobe Master' },
  { value: 'Hair and Makeup Supervisor', label: 'Hair and Makeup Supervisor' },
  { value: 'Sound Supervisor', label: 'Sound Supervisor' },
  { value: 'Video Supervisor', label: 'Video Supervisor' },
  { value: 'Projection Supervisor', label: 'Projection Supervisor' },
  { value: 'Automation Supervisor', label: 'Automation Supervisor' },
  { value: 'Pyrotechnics Supervisor', label: 'Pyrotechnics Supervisor' },
  { value: 'Special Effects Supervisor', label: 'Special Effects Supervisor' },
  { value: 'Production Designer', label: 'Production Designer' },
  { value: 'Art Director', label: 'Art Director' },
  { value: 'Assistant Art Director', label: 'Assistant Art Director' },
  { value: 'Set Designer', label: 'Set Designer' },
  { value: 'Storyboard Artist', label: 'Storyboard Artist' },
  { value: 'Concept Artist', label: 'Concept Artist' },
  { value: 'Matte Painter', label: 'Matte Painter' },
  { value: 'Digital Matte Painter', label: 'Digital Matte Painter' },
  { value: 'Rotoscope Artist', label: 'Rotoscope Artist' },
  { value: 'Paint Artist', label: 'Paint Artist' },
  { value: 'Clean-up Artist', label: 'Clean-up Artist' },
  { value: 'Inbetween Artist', label: 'Inbetween Artist' },
  { value: 'Key Animator', label: 'Key Animator' },
  { value: 'Character Animator', label: 'Character Animator' },
  { value: 'Background Animator', label: 'Background Animator' },
  { value: 'Effects Animator', label: 'Effects Animator' },
  { value: 'Layout Artist', label: 'Layout Artist' },
  { value: 'Background Artist', label: 'Background Artist' },
  { value: 'Color Stylist', label: 'Color Stylist' },
  { value: 'Color Key Artist', label: 'Color Key Artist' },
  { value: 'Color Designer', label: 'Color Designer' },
  { value: 'Visual Development Artist', label: 'Visual Development Artist' },
  { value: 'Character Designer', label: 'Character Designer' },
  { value: 'Environment Designer', label: 'Environment Designer' },
  { value: 'Prop Designer', label: 'Prop Designer' },
  { value: 'Vehicle Designer', label: 'Vehicle Designer' },
  { value: 'Creature Designer', label: 'Creature Designer' },
  { value: 'Character Modeler', label: 'Character Modeler' },
  { value: 'Environment Modeler', label: 'Environment Modeler' },
  { value: 'Prop Modeler', label: 'Prop Modeler' },
  { value: 'Vehicle Modeler', label: 'Vehicle Modeler' },
  { value: 'Creature Modeler', label: 'Creature Modeler' },
  { value: 'Organic Modeler', label: 'Organic Modeler' },
  { value: 'Hard Surface Modeler', label: 'Hard Surface Modeler' },
  { value: 'Architectural Modeler', label: 'Architectural Modeler' },
  { value: 'Character Rigger', label: 'Character Rigger' },
  { value: 'Facial Rigger', label: 'Facial Rigger' },
  { value: 'Body Rigger', label: 'Body Rigger' },
  { value: 'Vehicle Rigger', label: 'Vehicle Rigger' },
  { value: 'Prop Rigger', label: 'Prop Rigger' },
  { value: 'Creature Rigger', label: 'Creature Rigger' },
  { value: 'Technical Animator', label: 'Technical Animator' },
  { value: 'Pipeline Technical Director', label: 'Pipeline Technical Director' },
  { value: 'Tools Technical Director', label: 'Tools Technical Director' },
  { value: 'Rendering Technical Director', label: 'Rendering Technical Director' },
  { value: 'Lighting Technical Director', label: 'Lighting Technical Director' },
  { value: 'Shading Technical Director', label: 'Shading Technical Director' },
  { value: 'Effects Technical Director', label: 'Effects Technical Director' },
  { value: 'Simulation Technical Director', label: 'Simulation Technical Director' },
  { value: 'Cloth Technical Director', label: 'Cloth Technical Director' },
  { value: 'Hair Technical Director', label: 'Hair Technical Director' },
  { value: 'Fur Technical Director', label: 'Fur Technical Director' },
  { value: 'Fluid Technical Director', label: 'Fluid Technical Director' },
  { value: 'Particle Technical Director', label: 'Particle Technical Director' },
  { value: 'Destruction Technical Director', label: 'Destruction Technical Director' },
  { value: 'Crowd Technical Director', label: 'Crowd Technical Director' },
  { value: 'Character Technical Director', label: 'Character Technical Director' },
  { value: 'Rigging Technical Director', label: 'Rigging Technical Director' },
  { value: 'Animation Technical Director', label: 'Animation Technical Director' },
  { value: 'Modeling Technical Director', label: 'Modeling Technical Director' },
  { value: 'Texture Technical Director', label: 'Texture Technical Director' },
  { value: 'Look Development Technical Director', label: 'Look Development Technical Director' },
  { value: 'Pipeline Developer', label: 'Pipeline Developer' },
  { value: 'Tools Developer', label: 'Tools Developer' },
  { value: 'Rendering Developer', label: 'Rendering Developer' },
  { value: 'Lighting Developer', label: 'Lighting Developer' },
  { value: 'Shading Developer', label: 'Shading Developer' },
  { value: 'Effects Developer', label: 'Effects Developer' },
  { value: 'Simulation Developer', label: 'Simulation Developer' },
  { value: 'Cloth Developer', label: 'Cloth Developer' },
  { value: 'Hair Developer', label: 'Hair Developer' },
  { value: 'Fur Developer', label: 'Fur Developer' },
  { value: 'Fluid Developer', label: 'Fluid Developer' },
  { value: 'Particle Developer', label: 'Particle Developer' },
  { value: 'Destruction Developer', label: 'Destruction Developer' },
  { value: 'Crowd Developer', label: 'Crowd Developer' },
  { value: 'Character Developer', label: 'Character Developer' },
  { value: 'Rigging Developer', label: 'Rigging Developer' },
  { value: 'Animation Developer', label: 'Animation Developer' },
  { value: 'Modeling Developer', label: 'Modeling Developer' },
  { value: 'Texture Developer', label: 'Texture Developer' },
  { value: 'Look Development Developer', label: 'Look Development Developer' },
  { value: 'Pipeline Engineer', label: 'Pipeline Engineer' },
  { value: 'Tools Engineer', label: 'Tools Engineer' },
  { value: 'Rendering Engineer', label: 'Rendering Engineer' },
  { value: 'Lighting Engineer', label: 'Lighting Engineer' },
  { value: 'Shading Engineer', label: 'Shading Engineer' },
  { value: 'Effects Engineer', label: 'Effects Engineer' },
  { value: 'Simulation Engineer', label: 'Simulation Engineer' },
  { value: 'Cloth Engineer', label: 'Cloth Engineer' },
  { value: 'Hair Engineer', label: 'Hair Engineer' },
  { value: 'Fur Engineer', label: 'Fur Engineer' },
  { value: 'Fluid Engineer', label: 'Fluid Engineer' },
  { value: 'Particle Engineer', label: 'Particle Engineer' },
  { value: 'Destruction Engineer', label: 'Destruction Engineer' },
  { value: 'Crowd Engineer', label: 'Crowd Engineer' },
  { value: 'Character Engineer', label: 'Character Engineer' },
  { value: 'Rigging Engineer', label: 'Rigging Engineer' },
  { value: 'Animation Engineer', label: 'Animation Engineer' },
  { value: 'Modeling Engineer', label: 'Modeling Engineer' },
  { value: 'Texture Engineer', label: 'Texture Engineer' },
  { value: 'Look Development Engineer', label: 'Look Development Engineer' },
  { value: 'Pipeline Architect', label: 'Pipeline Architect' },
  { value: 'Tools Architect', label: 'Tools Architect' },
  { value: 'Rendering Architect', label: 'Rendering Architect' },
  { value: 'Lighting Architect', label: 'Lighting Architect' },
  { value: 'Shading Architect', label: 'Shading Architect' },
  { value: 'Effects Architect', label: 'Effects Architect' },
  { value: 'Simulation Architect', label: 'Simulation Architect' },
  { value: 'Cloth Architect', label: 'Cloth Architect' },
  { value: 'Hair Architect', label: 'Hair Architect' },
  { value: 'Fur Architect', label: 'Fur Architect' },
  { value: 'Fluid Architect', label: 'Fluid Architect' },
  { value: 'Particle Architect', label: 'Particle Architect' },
  { value: 'Destruction Architect', label: 'Destruction Architect' },
  { value: 'Crowd Architect', label: 'Crowd Architect' },
  { value: 'Character Architect', label: 'Character Architect' },
  { value: 'Rigging Architect', label: 'Rigging Architect' },
  { value: 'Animation Architect', label: 'Animation Architect' },
  { value: 'Modeling Architect', label: 'Modeling Architect' },
  { value: 'Texture Architect', label: 'Texture Architect' },
  { value: 'Look Development Architect', label: 'Look Development Architect' },
  { value: 'Pipeline Manager', label: 'Pipeline Manager' },
  { value: 'Tools Manager', label: 'Tools Manager' },
  { value: 'Rendering Manager', label: 'Rendering Manager' },
  { value: 'Lighting Manager', label: 'Lighting Manager' },
  { value: 'Shading Manager', label: 'Shading Manager' },
  { value: 'Effects Manager', label: 'Effects Manager' },
  { value: 'Simulation Manager', label: 'Simulation Manager' },
  { value: 'Cloth Manager', label: 'Cloth Manager' },
  { value: 'Hair Manager', label: 'Hair Manager' },
  { value: 'Fur Manager', label: 'Fur Manager' },
  { value: 'Fluid Manager', label: 'Fluid Manager' },
  { value: 'Particle Manager', label: 'Particle Manager' },
  { value: 'Destruction Manager', label: 'Destruction Manager' },
  { value: 'Crowd Manager', label: 'Crowd Manager' },
  { value: 'Character Manager', label: 'Character Manager' },
  { value: 'Rigging Manager', label: 'Rigging Manager' },
  { value: 'Animation Manager', label: 'Animation Manager' },
  { value: 'Modeling Manager', label: 'Modeling Manager' },
  { value: 'Texture Manager', label: 'Texture Manager' },
  { value: 'Look Development Manager', label: 'Look Development Manager' },
  { value: 'Pipeline Supervisor', label: 'Pipeline Supervisor' },
  { value: 'Tools Supervisor', label: 'Tools Supervisor' },
  { value: 'Rendering Supervisor', label: 'Rendering Supervisor' },
  { value: 'Lighting Supervisor', label: 'Lighting Supervisor' },
  { value: 'Shading Supervisor', label: 'Shading Supervisor' },
  { value: 'Effects Supervisor', label: 'Effects Supervisor' },
  { value: 'Simulation Supervisor', label: 'Simulation Supervisor' },
  { value: 'Cloth Supervisor', label: 'Cloth Supervisor' },
  { value: 'Hair Supervisor', label: 'Hair Supervisor' },
  { value: 'Fur Supervisor', label: 'Fur Supervisor' },
  { value: 'Fluid Supervisor', label: 'Fluid Supervisor' },
  { value: 'Particle Supervisor', label: 'Particle Supervisor' },
  { value: 'Destruction Supervisor', label: 'Destruction Supervisor' },
  { value: 'Crowd Supervisor', label: 'Crowd Supervisor' },
  { value: 'Character Supervisor', label: 'Character Supervisor' },
  { value: 'Rigging Supervisor', label: 'Rigging Supervisor' },
  { value: 'Animation Supervisor', label: 'Animation Supervisor' },
  { value: 'Modeling Supervisor', label: 'Modeling Supervisor' },
  { value: 'Texture Supervisor', label: 'Texture Supervisor' },
  { value: 'Look Development Supervisor', label: 'Look Development Supervisor' },
  { value: 'Pipeline Lead', label: 'Pipeline Lead' },
  { value: 'Tools Lead', label: 'Tools Lead' },
  { value: 'Rendering Lead', label: 'Rendering Lead' },
  { value: 'Lighting Lead', label: 'Lighting Lead' },
  { value: 'Shading Lead', label: 'Shading Lead' },
  { value: 'Effects Lead', label: 'Effects Lead' },
  { value: 'Simulation Lead', label: 'Simulation Lead' },
  { value: 'Cloth Lead', label: 'Cloth Lead' },
  { value: 'Hair Lead', label: 'Hair Lead' },
  { value: 'Fur Lead', label: 'Fur Lead' },
  { value: 'Fluid Lead', label: 'Fluid Lead' },
  { value: 'Particle Lead', label: 'Particle Lead' },
  { value: 'Destruction Lead', label: 'Destruction Lead' },
  { value: 'Crowd Lead', label: 'Crowd Lead' },
  { value: 'Character Lead', label: 'Character Lead' },
  { value: 'Rigging Lead', label: 'Rigging Lead' },
  { value: 'Animation Lead', label: 'Animation Lead' },
  { value: 'Modeling Lead', label: 'Modeling Lead' },
  { value: 'Texture Lead', label: 'Texture Lead' },
  { value: 'Look Development Lead', label: 'Look Development Lead' },
  { value: 'Pipeline Coordinator', label: 'Pipeline Coordinator' },
  { value: 'Tools Coordinator', label: 'Tools Coordinator' },
  { value: 'Rendering Coordinator', label: 'Rendering Coordinator' },
  { value: 'Lighting Coordinator', label: 'Lighting Coordinator' },
  { value: 'Shading Coordinator', label: 'Shading Coordinator' },
  { value: 'Effects Coordinator', label: 'Effects Coordinator' },
  { value: 'Simulation Coordinator', label: 'Simulation Coordinator' },
  { value: 'Cloth Coordinator', label: 'Cloth Coordinator' },
  { value: 'Hair Coordinator', label: 'Hair Coordinator' },
  { value: 'Fur Coordinator', label: 'Fur Coordinator' },
  { value: 'Fluid Coordinator', label: 'Fluid Coordinator' },
  { value: 'Particle Coordinator', label: 'Particle Coordinator' },
  { value: 'Destruction Coordinator', label: 'Destruction Coordinator' },
  { value: 'Crowd Coordinator', label: 'Crowd Coordinator' },
  { value: 'Character Coordinator', label: 'Character Coordinator' },
  { value: 'Rigging Coordinator', label: 'Rigging Coordinator' },
  { value: 'Animation Coordinator', label: 'Animation Coordinator' },
  { value: 'Modeling Coordinator', label: 'Modeling Coordinator' },
  { value: 'Texture Coordinator', label: 'Texture Coordinator' },
  { value: 'Look Development Coordinator', label: 'Look Development Coordinator' },
  { value: 'Pipeline Assistant', label: 'Pipeline Assistant' },
  { value: 'Tools Assistant', label: 'Tools Assistant' },
  { value: 'Rendering Assistant', label: 'Rendering Assistant' },
  { value: 'Lighting Assistant', label: 'Lighting Assistant' },
  { value: 'Shading Assistant', label: 'Shading Assistant' },
  { value: 'Effects Assistant', label: 'Effects Assistant' },
  { value: 'Simulation Assistant', label: 'Simulation Assistant' },
  { value: 'Cloth Assistant', label: 'Cloth Assistant' },
  { value: 'Hair Assistant', label: 'Hair Assistant' },
  { value: 'Fur Assistant', label: 'Fur Assistant' },
  { value: 'Fluid Assistant', label: 'Fluid Assistant' },
  { value: 'Particle Assistant', label: 'Particle Assistant' },
  { value: 'Destruction Assistant', label: 'Destruction Assistant' },
  { value: 'Crowd Assistant', label: 'Crowd Assistant' },
  { value: 'Character Assistant', label: 'Character Assistant' },
  { value: 'Rigging Assistant', label: 'Rigging Assistant' },
  { value: 'Animation Assistant', label: 'Animation Assistant' },
  { value: 'Modeling Assistant', label: 'Modeling Assistant' },
  { value: 'Texture Assistant', label: 'Texture Assistant' },
  { value: 'Look Development Assistant', label: 'Look Development Assistant' },
  { value: 'Pipeline Intern', label: 'Pipeline Intern' },
  { value: 'Tools Intern', label: 'Tools Intern' },
  { value: 'Rendering Intern', label: 'Rendering Intern' },
  { value: 'Lighting Intern', label: 'Lighting Intern' },
  { value: 'Shading Intern', label: 'Shading Intern' },
  { value: 'Effects Intern', label: 'Effects Intern' },
  { value: 'Simulation Intern', label: 'Simulation Intern' },
  { value: 'Cloth Intern', label: 'Cloth Intern' },
  { value: 'Hair Intern', label: 'Hair Intern' },
  { value: 'Fur Intern', label: 'Fur Intern' },
  { value: 'Fluid Intern', label: 'Fluid Intern' },
  { value: 'Particle Intern', label: 'Particle Intern' },
  { value: 'Destruction Intern', label: 'Destruction Intern' },
  { value: 'Crowd Intern', label: 'Crowd Intern' },
  { value: 'Character Intern', label: 'Character Intern' },
  { value: 'Rigging Intern', label: 'Rigging Intern' },
  { value: 'Animation Intern', label: 'Animation Intern' },
  { value: 'Modeling Intern', label: 'Modeling Intern' },
  { value: 'Texture Intern', label: 'Texture Intern' },
  { value: 'Look Development Intern', label: 'Look Development Intern' },
];

export const API_ENDPOINTS = {
  CUSTOMER_PROFILE: '/customer/storefront/customer/profile',
  COUNTRIES: '/location/backoffice/countries',
  STATE_OR_PROVINCES: '/location/storefront/state-or-provinces',
  DISTRICTS: '/location/storefront/district',
  CREATE_PROFILE: '/customer/storefront/customer/profile',
  UPDATE_PROFILE: '/customer/storefront/customer/profile',
} as const;
