import { ProfileApiResponse } from './types';

export const mockProfileData: ProfileApiResponse = {
  customer: {
    id: '1',
    username: 'phan.bich.a',
    email: 'PhanThiBichA@gmail.com',
    firstName: 'Phan Thi',
    lastName: 'Bich A',
  },
  applicantProfile: {
    id: 1,
    userId: '1',
    contactName: 'Phan Thi Bich A',
    firstName: 'Phan Thi',
    lastName: 'Bich A',
    phoneNumber: '+84 0982888860',
    religion: 'Buddhism',
    hometown: 'Hanoi',
    citizenshipStatus: 'Student Visa',
    ethnicity: 'Asian',
    race: 'Asian',
    militaryFamilyHistory: false,
    disabilities: '',
    medicalConditions: 'None',
    favoriteActivities: 'Piano, Painting, Theater Club',
    sportsParticipated: 'Basketball, Swimming',
    studentActivities: 'Debate Club, Math Olympiad Team',
    organizationsJoined: 'National Honor Society, Student Council',
    researchExperience: 'AI Research Assistant at University Lab',
    careerGoals: 'Software Engineer specializing in AI and Machine Learning',
    overallGpa: 3.2,
    certificates: [
      {
        id: 1,
        applicantId: 1,
        certificateName: 'AWS Certified Developer',
        issuedBy: 'Amazon Web Services',
        issueDate: '2024-01-15T00:00:00.000Z',
        expiryDate: '2027-01-15T00:00:00.000Z',
        score: 'Pass',
      },
      {
        id: 2,
        applicantId: 1,
        certificateName: 'Google Cloud Professional',
        issuedBy: 'Google Cloud',
        issueDate: '2023-06-20T00:00:00.000Z',
        expiryDate: '2025-06-20T00:00:00.000Z',
        score: '95/100',
      },
    ],
    educationHistories: [
      {
        id: 1,
        applicantId: 1,
        institutionName: 'Rochester College',
        institutionType: 'College',
        state: 'Michigan',
        country: 'USA',
        degreeType: "Bachelor's",
        majorCategory: 'Computer Science & Engineering',
        majorName: 'Computer Science',
        gpa: 3.2,
        classRank: 'Top 15%',
        classSize: 250,
        enrollmentStartDate: '2024-09-01T00:00:00.000Z',
        enrollmentEndDate: '2028-06-01T00:00:00.000Z',
        graduationYear: 2029,
        isDualEnrolled: false,
        isTransfer: false,
        isReturningStudent: false,
        notes: "Dean's List Fall 2024",
      },
      {
        id: 2,
        applicantId: 1,
        institutionName: 'Hanoi High School for Gifted Students',
        institutionType: 'High School',
        state: 'Hanoi',
        country: 'Vietnam',
        degreeType: 'High School Diploma',
        majorCategory: 'Science',
        majorName: 'Mathematics & Computer Science',
        gpa: 3.8,
        classRank: 'Valedictorian',
        classSize: 300,
        enrollmentStartDate: '2020-09-01T00:00:00.000Z',
        enrollmentEndDate: '2024-06-01T00:00:00.000Z',
        graduationYear: 2024,
        isDualEnrolled: false,
        isTransfer: false,
        isReturningStudent: false,
        notes: 'Perfect attendance, National Math Competition Winner',
      },
    ],
    applicantPreferences: [
      {
        id: 1,
        applicantId: 1,
        type: 'Location',
        value: 'Urban',
        weight: 8,
        note: 'Prefer urban campuses with access to tech companies',
      },
      {
        id: 2,
        applicantId: 1,
        type: 'Institution Size',
        value: 'Medium',
        weight: 6,
        note: 'Mid-sized universities (5,000-15,000 students)',
      },
      {
        id: 3,
        applicantId: 1,
        type: 'Major Focus',
        value: 'Computer Science',
        weight: 9,
        note: 'Strong CS program with AI/ML specialization',
      },
    ],
    skills: [
      {
        id: 1,
        applicantId: 1,
        skillName: 'JavaScript',
        proficiencyLevel: 'Advanced',
        yearsExperience: 3,
      },
      {
        id: 2,
        applicantId: 1,
        skillName: 'React',
        proficiencyLevel: 'Advanced',
        yearsExperience: 2,
      },
      {
        id: 3,
        applicantId: 1,
        skillName: 'Node.js',
        proficiencyLevel: 'Intermediate',
        yearsExperience: 2,
      },
      {
        id: 4,
        applicantId: 1,
        skillName: 'Python',
        proficiencyLevel: 'Intermediate',
        yearsExperience: 1,
      },
    ],
    intentions: [
      {
        id: 1,
        applicantId: 1,
        intendedInstitution: 'Rochester College',
        intendedState: 'Michigan',
        intendedCountry: 'USA',
        degreeType: "Bachelor's",
        intendedMajorCategory: 'Computer Science & Engineering',
        intendedMajorName: 'Computer Science with AI Specialization',
        academicClassification: 'College Freshman',
        expectedStartDate: '2024-09-01T00:00:00.000Z',
        expectedGraduationYear: 2029,
        isTransferStudent: false,
        isReturningStudent: false,
        notes: 'Planning to pursue minor in Mathematics',
      },
    ],
  },
  providerProfile: null,
};
