CREATE TABLE IF NOT EXISTS profile.PROVIDER_FAVOURITE (
    ID BIGSERIAL PRIMARY KEY,
    PROVIDER_ID BIGINT NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    NOTE TEXT NULL,

    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION NUMERIC NOT NULL DEFAULT 0,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);