CREATE TABLE IF NOT EXISTS profile.PROVIDER_CODE_VERIFIED (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID VARCHAR(128) NOT NULL,
    CODE VARCHAR(6) NOT NULL,
    EXPIRED_TIME TIMESTAMP,
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION NUMERIC NOT NULL DEFAULT 0,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
