ALTER TABLE profile.APPLICANT_PROFILE
    -- Trình độ học vấn
    ADD COLUMN EDUCATION_LEVEL VARCHAR(100),

    -- Điểm các kỳ thi chuẩn hóa
    ADD COLUMN SAT_SCORE INT,
    ADD COLUMN ACT_SCORE INT,
    ADD COLUMN TOEFL_SCORE INT,
    ADD COLUMN IELTS_SCORE DOUBLE PRECISION,
    ADD COLUMN GRE_SCORE INT,
    ADD COLUMN GMAT_SCORE INT,

    -- Ngôn ngữ
    ADD COLUMN LANGUAGES TEXT,

    -- Thành tích học thuật, giải thưởng, số bài nghiên cứu
    ADD COLUMN ACADEMIC_AWARDS TEXT,
    ADD COLUMN PUBLICATION_COUNT INT,
    ADD COLUMN RESEARCH_INTEREST TEXT,

    -- Hoạt động ngoại khóa, tình nguyện
    ADD COLUMN EXTRACURRICULAR_ACTIVITIES TEXT,

    -- Loại học bổng mong muốn
    ADD COLUMN PREFERRED_SCHOLARSHIP_TYPE VARCHAR(100),

    -- Quốc gia/university mong muốn
    ADD COLUMN PREFERRED_COUNTRY VARCHAR(100),
    ADD COLUMN PREFERRED_UNIVERSITY VARCHAR(255);