version: "1.0.0"

services:
  nextjs:
    ports:
      - 3024:3024
    container_name: back_office
    image: back_office:latest
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
