import { IApplication } from "@/lib/schemas";

export const DEFAULT_APPLICATION_FORM_VALUES: IApplication = {
  id: undefined,
  applicationName: "Application",
  code: "",
  versionApplication: 1,
  fullName: "",
  gender: "",
  dateOfBirth: "",
  email: "",
  phone: "",
  address: "",
  nationality: "",
  educationLevel: "",
  schoolName: "",
  major: "",
  gpa: 0,
  graduationYear: "",
  skills: "",
  achievements: "",
  extracurricular: "",
  motivation: "",
  personalStatement: "",
  languages: "",
  careerGoal: "",
  researchInterest: "",
  academicAwards: "",
  publicationCount: undefined,
  satScore: undefined,
  actScore: undefined,
  greScore: undefined,
  gmatScore: undefined,
  toeflScore: undefined,
  ieltsScore: undefined,
  workExperienceYears: undefined,
  classRank: undefined,
  classSize: undefined,
  classRankPercentile: undefined,
  age: undefined,
  citizenship: "",
  isAthlete: false,
  athleticAchievements: "",
  applicationAttributes: [],
};
