CREATE SCHEMA IF NOT EXISTS notification;

CREATE TABLE IF NOT EXISTS notification.USER_NOTIFICATION (
    id BIGSERIAL PRIMARY KEY,
    NOTIFICATION_ID BIGINT,
    USER_ID VARCHAR(100),
    IS_READ BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_BY                      VARCHAR(32) DEFAULT '',
    UPDATED_BY                      VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION NUMERIC NOT NULL DEFAULT 0,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notification.NOTIFICATION_TEMPLATE (
    id BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(512),
    CONTENT TEXT,
    TYPE VARCHAR(100),
    REFERENCE_TYPE VARCHAR(100),
    REFERENCE_ID BIGINT,
    CREATED_BY                      VARCHAR(32) DEFAULT '',
    UPDATED_BY                      VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION NUMERIC NOT NULL DEFAULT 0,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
