CREATE SCHEMA IF NOT EXISTS location;

CREATE TABLE IF NOT EXISTS location.country (
                                                id BIGSERIAL PRIMARY KEY,
                                                NAME VARCHAR(450) NOT NULL,
    CODE_2 VARCHAR(3),
    CODE3 VARCHAR(3),
    IS_BILLING_ENABLED BOOLEAN,
    IS_SHIPPING_ENABLED BOOLEAN,
    IS_CITY_ENABLED BOOLEAN,
    IS_ZIP_CODE_ENABLED BOOLEAN,
    IS_DISTRICT_ENABLED BOOLEAN,
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN DEFAULT TRUE,
    VERSION NUMERIC DEFAULT 0,
    CREATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS location.state_or_province (
                                                          id BIGSERIAL PRIMARY KEY,
                                                          CODE VARCHAR(255),
    NAME VARCHAR(450) NOT NULL,
    TYPE VARCHAR(255),
    COUNTRY_ID BIGINT NOT NULL,
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN DEFAULT TRUE,
    VERSION NUMERIC DEFAULT 0,
    CREATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_state_country FOREIGN KEY (country_id) REFERENCES location.country(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS location.district (
                                                 id BIGSERIAL PRIMARY KEY,
                                                 NAME VARCHAR(450) NOT NULL,
    TYPE VARCHAR(450),
    LOCATION TEXT,
    STATE_OR_PROVINCE_ID BIGINT NOT NULL,
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN DEFAULT TRUE,
    VERSION NUMERIC DEFAULT 0,
    CREATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_district_state FOREIGN KEY (state_or_province_id) REFERENCES location.state_or_province(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS location.address (
                                                id BIGSERIAL PRIMARY KEY,
                                                CONTACT_NAME VARCHAR(450),
    PHONE VARCHAR(25),
    ADDRESS_LINE_1 VARCHAR(450),
    ADDRESS_LINE_2 VARCHAR(450),
    CITY VARCHAR(450),
    ZIP_CODE VARCHAR(25),
    DISTRICT_ID BIGINT NOT NULL,
    STATE_OR_PROVINCE_ID BIGINT NOT NULL,
    COUNTRY_ID BIGINT NOT NULL,
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN DEFAULT TRUE,
    VERSION NUMERIC DEFAULT 0,
    CREATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_address_district FOREIGN KEY (district_id) REFERENCES location.district(id) ON DELETE CASCADE,
    CONSTRAINT fk_address_state FOREIGN KEY (state_or_province_id) REFERENCES location.state_or_province(id) ON DELETE CASCADE,
    CONSTRAINT fk_address_country FOREIGN KEY (country_id) REFERENCES location.country(id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_state_country    ON location.state_or_province(country_id);
CREATE INDEX IF NOT EXISTS idx_district_state   ON location.district(state_or_province_id);
CREATE INDEX IF NOT EXISTS idx_address_district ON location.address(district_id);
CREATE INDEX IF NOT EXISTS idx_address_state    ON location.address(state_or_province_id);
CREATE INDEX IF NOT EXISTS idx_address_country  ON location.address(country_id);
