CREATE SCHEMA IF NOT EXISTS customer;

create table IF NOT EXISTS customer.USER_ADDRESS (
    id bigserial not null,
    USER_ID varchar(255) not null,
    ADDRESS_ID bigserial not null,
    IS_ACTIVE boolean,
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION NUMERIC NOT NULL DEFAULT 0,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    primary key(id));

create table IF NOT EXISTS customer.PROVIDER_ADDRESS (
    id bigserial not null,
    PROVIDER_ID bigserial not null,
    ADDRESS_ID bigserial not null,
    IS_ACTIVE boolean,
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION NUMERIC NOT NULL DEFAULT 0,
    CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    primary key(id));