CREATE SCHEMA IF NOT EXISTS customer;

create table customer.USER_ADDRESS (
    id bigserial not null,
    CREATED_BY VARCHAR(32) DEFAULT '',
    UPDATED_BY VARCHAR(32) DEFAULT '',
    ACTIVE BOOLEAN DEFAULT TRUE,
    VERSION NUMERIC DEFAULT 0,
    CREATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_ID varchar(255) not null,
    ADDRESS_ID bigserial not null,
    IS_ACTIVE boolean,
    primary key(id))