# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13AlSaNvGkLEnbW51uXdGu-RIE-7Hpa8y
"""


import json
import re

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

from google import genai

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import torch

import psycopg2
from psycopg2 import Error

# Thông tin kết nối
DB_SCHOLARSHIP = {
    'host': '160.30.113.224',
    'port': '5432',
    'database': 'scholarship',
    'user': 'admin',
    'password': 'minh01672527656'
}

DB_PROFILE = {
    'host': '160.30.113.224',
    'port': '5432',
    'database': 'profile',
    'user': 'admin',
    'password': 'minh01672527656'
}

def connect_database():
    """Kết nối đến PostgreSQL database"""
    try:
        # Tạo kết nối
        scholarship_connection = psycopg2.connect(
            host=DB_SCHOLARSHIP['host'],
            port=DB_SCHOLARSHIP['port'],
            database=DB_SCHOLARSHIP['database'],
            user=DB_SCHOLARSHIP['user'],
            password=DB_SCHOLARSHIP['password']
        )

        profile_connection = psycopg2.connect(
            host=DB_PROFILE['host'],
            port=DB_PROFILE['port'],
            database=DB_PROFILE['database'],
            user=DB_PROFILE['user'],
            password=DB_PROFILE['password']
        )

        scholarship_connection.autocommit = True
        profile_connection.autocommit = True

        # Tạo cursor
        scholarship_cursor = scholarship_connection.cursor()
        profile_cursor = profile_connection.cursor()

        return scholarship_connection, scholarship_cursor, profile_connection, profile_cursor

    except Error as e:
        print(f"✗ Lỗi kết nối database: {e}")
        return None, None

def close_connection(connection, cursor):
    """Đóng kết nối database"""
    if cursor:
        cursor.close()
    if connection:
        connection.close()
        print("\n✓ Đã đóng kết nối database")

def all_scholarships_query(cursor):
    """Trả dữ liệu scholarship + preference dạng JSON"""

    query = """
        SELECT
            s.id,
            s.title,
            s.description,
            s.requirements,
            s.fields,
            s.country,
            s.study_level,
            s.language_requirement,
            s.gpa_requirement,

            COALESCE(
                json_agg(
                    json_build_object(
                        'type', sp.type,
                        'value', sp.value,
                        'note', sp.note
                    )
                ) FILTER (WHERE sp.type IS NOT NULL),
                '[]'
            ) AS scholarship_preferences

        FROM scholarship.scholarship s
        LEFT JOIN scholarship.scholarship_preference sp
            ON s.id = sp.scholarship_id
        GROUP BY s.id
    """

    cursor.execute(query)
    rows = cursor.fetchall()
    col_names = [desc[0] for desc in cursor.description]

    result = {}
    for row in rows:
        item = dict(zip(col_names, row))
        result[item["id"]] = item

    return result

def application_query(cursor, scholarship_id):
    """Trả dữ liệu scholarship + preference dạng JSON"""

    query = f"""
        SELECT
            a.id,
            a.nationality,
            a.education_level,
            a.major,
            a.gpa,
            a.graduation_year,
            a.skills,
            a.languages,
            a.achievements,
            a.extracurricular,
            a.motivation,
            a.personal_statement,

            COALESCE(
                json_agg(
                    json_build_object(
                        'key', at.key,
                        'value', at.value,
                        'note', at.note
                    )
                ) FILTER (WHERE at.key IS NOT NULL),
                '[]'
            ) AS application_attributes

        FROM scholarship.application a
        LEFT JOIN scholarship.application_attribute at
            ON a.id = at.application_id
        JOIN scholarship.application_scholarship asch
            ON a.id = asch.application_id
        WHERE asch.scholarship_id = {scholarship_id}
        GROUP BY a.id

    """

    cursor.execute(query)
    rows = cursor.fetchall()
    col_names = [desc[0] for desc in cursor.description]

    result = {}
    for row in rows:
        item = dict(zip(col_names, row))
        result[item["id"]] = item

    return result

def all_applicant_profile_query(cursor):
    """Trả dữ liệu profile + preference dạng JSON"""
    query = f"""
        SELECT
          ap.id,
          ap.hometown,
          ap.career_goals,
          ap.overall_gpa,
          COALESCE(
                  json_agg(
                      json_build_object(
                          'type', apf.type,
                          'value', apf.value,
                          'note', apf.note
                      )
                  ) FILTER (WHERE apf.type IS NOT NULL),
                  '[]'
              ) AS applicant_preferences,
              COALESCE(
                  json_agg(
                      json_build_object(
                          'name', ac.certificate_name,
                          'score', ac.score
                      )
                  ) FILTER (WHERE apf.type IS NOT NULL),
                  '[]'
              ) AS applicant_certificates,
              COALESCE(
                  json_agg(
                      json_build_object(
                          'name', ask.skill_name,
                          'level', ask.proficiency_level,
                          'years_experience', ask.years_experience
                      )
                  ) FILTER (WHERE apf.type IS NOT NULL),
                  '[]'
              ) AS applicant_skills,
              COALESCE(
                  json_agg(
                      json_build_object(
                          'institution_type', aeh.institution_type,
                          'major_name', aeh.major_name,
                          'gpa', aeh.gpa
                      )
                  ) FILTER (WHERE apf.type IS NOT NULL),
                  '[]'
              ) AS applicant_education_history
        FROM profile.applicant_profile ap
        LEFT JOIN profile.applicant_preference apf
            ON ap.id = apf.applicant_id
        LEFT JOIN profile.applicant_certificate ac
            ON ap.id = ac.applicant_id
        LEFT JOIN profile.applicant_skill ask
            ON ap.id = ask.applicant_id
        LEFT JOIN profile.applicant_education_history aeh
            ON ap.id = aeh.applicant_id
        GROUP BY ap.id
    """

    cursor.execute(query)
    rows = cursor.fetchall()
    col_names = [desc[0] for desc in cursor.description]

    result = {}
    for row in rows:
        item = dict(zip(col_names, row))
        result[item["id"]] = item

    return result

sch_conn, sch_cur, prof_conn, prof_cur = connect_database()

def create_scholarship_text(scholarship):
    """Tạo chuỗi mô tả học bổng từ dict scholarship."""

    # Preferences
    prefs = ", ".join(
        p.get("note", "") for p in scholarship.get("scholarshipPreferences", [])
    ) or "None"

    # Các thông tin chính, dùng get để tránh KeyError
    title = scholarship.get("title", "N/A")
    description = scholarship.get("description", "N/A")
    country = scholarship.get("country", "N/A")
    fields = ", ".join(scholarship.get("fields", [])) if isinstance(scholarship.get("fields"), list) else scholarship.get("fields", "N/A")
    level = scholarship.get("studyLevel", "N/A")
    gpa_req = scholarship.get("gpaRequirement", "N/A")
    lang_req = scholarship.get("languageRequirement", "N/A")

    # Tạo text
    text = (
        f"Scholarship Title: {title}\n"
        f"Description: {description}\n"
        f"Country: {country}\n"
        f"Fields: {fields}\n"
        f"Level: {level}\n"
        f"Requirements:\n"
        f"  - GPA: {gpa_req}\n"
        f"  - Language: {lang_req}\n"
        f"Preferences: {prefs}"
    )

    return text

def create_application_text(application):
    """Tạo query từ hồ sơ sinh viên – rõ ràng, sạch, tối ưu cho embedding."""

    # Chuẩn hoá giá trị rỗng
    lang = application.get("language") or "None"
    skills = application.get("skills") or "None"
    achievements = application.get("achievements") or "None"
    background = application.get("personalStatement") or "None"
    nationality = application.get("nationality") or "Unknown"


    prefs = ", ".join(pref.get("note", "") for pref in application.get("applicationAttributes", []))

    query = f"""
Student seeking {application.get('educationLevel', 'N/A')} scholarship in {application.get('major', 'N/A')}

Academic:
  - GPA: {application.get('gpa', 'N/A')}

Skills:
  {skills}

Language:
  {lang}

Achievements:
  {achievements}

Background:
  {background}

Nationality:
  {nationality}

Preferences:
  {prefs}
    """

    return query.strip()

def create_applicant_text(applicant):
    """Tạo query từ hồ sơ sinh viên, bao gồm education, skills và intentions."""

    # Preferences
    prefs = ", ".join(pref.get("note", "") for pref in applicant.get("applicantPreferences", []))

    # Education histories
    education_histories_text = "\n".join(
        f"  - Institution Type: {edu.get('institutionType', 'N/A')}\n"
        f"    Major Category: {edu.get('majorCategory', 'N/A')}\n"
        f"    GPA: {edu.get('gpa', 'N/A')}\n"
        for edu in applicant.get("educationHistories", [])
    )

    # Skills
    skills_list_text = "\n".join(
        f"  - Name: {skill.get('skillName', 'N/A')}\n"
        f"    Level: {skill.get('proficiencyLevel', 'N/A')}\n"
        for skill in applicant.get('skills', [])
    )


    # Tạo query tổng hợp
    query = f"""
Hometown: {applicant.get('hometown', 'N/A')}
Career goals: {applicant.get('careerGoals', 'N/A')}
Overall GPA: {applicant.get('overallGpa', 'N/A')}
Language: {applicant.get('language', 'N/A')}

Education histories:
{education_histories_text}

Preferences: {prefs}

Skills:
{skills_list_text}
    """

    return query.strip()

emb_model = SentenceTransformer('all-MiniLM-L6-v2')

def normalize(text):
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def get_embedding(text, model=emb_model):
    """Lấy embedding vector"""
    text = text.replace("\n", " ")
    response = model.encode(text)
    return response

def embedding_scholarships(scholarships):
    scholarship_embeddings = []
    scholarships_list  = list(scholarships.values())
    for scholarship in scholarships_list:
        text = create_scholarship_text(scholarship)
        embedding = get_embedding(normalize(text))
        scholarship_embeddings.append({
            "id": scholarship["id"],
            "scholarship": scholarship,
            "embedding": embedding
        })
    return scholarship_embeddings

def embedding_applicants(applicants):
    applicant_embeddings = []
    applicants_list  = list(applicants.values())
    for applicant in applicants_list:
        text = create_applicant_text(applicant)
        embedding = get_embedding(normalize(text))
        applicant_embeddings.append({
            "id": applicant["id"],
            "applicant": applicant,
            "embedding": embedding
        })
    return applicant_embeddings

def embedding_applications(applications):
    application_embeddings = []
    applications_list  = list(applications.values())
    for application in applications_list:
        text = create_application_text(application)
        embedding = get_embedding(normalize(text))
        application_embeddings.append({
            "id": application["id"],
            "application": application,
            "embedding": embedding
        })
    return application_embeddings

def scholarships_search(applicant_id, top_k=5):
    """Tìm kiếm học bổng phù hợp nhất"""
    # Tạo query embedding
    applicant = all_applicants_list.get(applicant_id)

    query = create_applicant_text(applicant)
    query_embedding = get_embedding(query)

    # Tính similarity
    scores = []

    for item in scholarships_emb:
        similarity = cosine_similarity(
            [query_embedding],
            [item["embedding"]]
        )[0][0]
        scores.append({
            "scholarship": item["scholarship"]["id"],
            "similarity_score": similarity
        })

    # Sắp xếp và lấy top K
    scores.sort(key=lambda x: x["similarity_score"], reverse=True)
    return scores[:top_k]

def applicant_search(scholarship_id, top_k=5):
    """Tìm kiếm các applicant phù hợp nhất với một học bổng"""
    scholarship = all_scholarships_list.get(scholarship_id)

    # Tạo query embedding từ học bổng
    query = create_scholarship_text(scholarship)
    query_embedding = get_embedding(query)

    # Tính similarity với tất cả applicants
    scores = []
    for item in applicants_emb:
        similarity = cosine_similarity(
            [query_embedding],
            [item["embedding"]]
        )[0][0]
        scores.append({
            "applicant": item["applicant"]["id"],
            "similarity_score": similarity
        })

    # Sắp xếp theo similarity giảm dần và lấy top K
    scores.sort(key=lambda x: x["similarity_score"], reverse=True)
    return scores[:top_k]

def application_search(scholarship_id, top_k=5):
    """Tìm kiếm các applicant phù hợp nhất với một học bổng"""
    scholarship = all_scholarships_list.get(scholarship_id)

    applications_list = application_query(sch_cur, scholarship_id)

    applications_emb = embedding_applications(applications_list)

    # Tạo query embedding từ học bổng
    query = create_scholarship_text(scholarship)
    query_embedding = get_embedding(query)

    # Tính similarity với tất cả applicants
    scores = []
    for item in applications_emb:
        similarity = cosine_similarity(
            [query_embedding],
            [item["embedding"]]
        )[0][0]
        scores.append({
            "application": item["application"]["id"],
            "similarity_score": similarity
        })

    # Sắp xếp theo similarity giảm dần và lấy top K
    scores.sort(key=lambda x: x["similarity_score"], reverse=True)
    return scores[:top_k]

def llm_analyze(applicant_id, scholarship_id):

    # Build scholarship text

    scholarship = all_scholarships_list.get(scholarship_id)
    applicant = all_applicants_list.get(applicant_id)

    scholarship_text = create_scholarship_text(scholarship)
    applicant_text = create_applicant_text(applicant)

    # Build prompt
    prompt = f"""
You are a professional scholarship evaluation system.
Your task is to evaluate the match between a student and a scholarship and return the result as valid JSON only.

========================
STUDENT PROFILE
========================
{applicant_text}

========================
SCHOLARSHIP DETAILS
========================
{scholarship_text}

Pay close attention to:
- Required GPA vs Student GPA
- Required language levels (IELTS / TOEFL / JLPT / HSK) vs Student language proficiency
- If the student's language proficiency is lower than the scholarship requirement:
  * Do NOT generate positive match reasons based on language.
  * Instead, clearly mention language as an area for improvement in improvement_areas.
  * Add specific advice in application_tips on how to improve language scores before applying.
- Required study level vs Student current/target level
- Required major/fields vs Student major or related expertise
- Explicit eligibility constraints (country restrictions, background requirements, etc.)


If either the scholarship or the applicant includes preference information, prioritize these preferences when evaluating compatibility.
========================
TASKS
========================
1. Evaluate how well the student matches the scholarship.
2. For the scholarship, provide:
   - match_reasons: Why the student is a good match (1-2)
        (- If the student's GPA is lower than the scholarship's required GPA:
            * Do NOT generate any positive GPA-related match reasons.
            * Do NOT say the GPA is 'close', 'almost meets', or 'acceptable'.
            * Instead, clearly mark GPA as a weakness in improvement_areas.)
   - student_strengths: Specific strengths relevant to this scholarship (2-3)
   - improvement_areas: Things the student should improve (2-3)
   - application_tips: Tips to maximize acceptance chance (2-3)

3. Provide overall_strategy for the student.
4. Provide timeline for preparing documents, exams, and submission.



========================
RESPONSE RULES
========================
- Keep all text concise; do not write long explanations.
- Do not use **
- Return ONLY valid JSON.
- No Markdown, no explanation, no text before or after JSON.
- Do NOT include ```json markers.
- Do NOT use any Markdown formatting, especially no ** for bold.
- Ensure JSON is well-formed (no trailing commas).
- All fields MUST follow this structure:

{{
  "recommendations": [
    {{
      "scholarship_name": "",
      "match_reasons": [],
      "student_strengths": [],
      "improvement_areas": [],
      "application_tips": []
    }}
  ],
  "overall_strategy": "",
  "timeline": []
}}

Generate JSON now.
"""
    client = genai.Client(api_key="AIzaSyBwEhVB3czCxH1ddkZ07vB-ivulILYN7xs")

    response = client.models.generate_content(
      model="gemini-2.5-flash", contents=prompt
    )

    return response.text

#sch_conn, sch_cur, prof_conn, prof_cur = connect_database()

#all_scholarships_list = all_scholarships_query(sch_cur)


#all_applicants_list = all_applicant_profile_query(prof_cur)

#scholarships_emb = embedding_scholarships(all_scholarships_list)

#applicants_emb = embedding_applicants(all_applicants_list)

#recommend_scholarship = scholarships_search(3)

#recommend_applicant = applicant_search(65)

#recommend_application = application_search(65)

#recommend_applicant